/*
 * SPDX-FileCopyrightText: 2026 Paul Galbraith
 * SPDX-License-Identifier: GPL-3.0-only
 */

#ifndef REMANENCE_H
#define REMANENCE_H

/* Generated by cbindgen from crates/remanence-ffi. Do not edit by hand. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

// Stable, machine-readable classification of a library refusal. A fallible
// call writes one beside its error message; the output is untouched on success.
typedef enum {
  REMANENCE_ERROR_CATEGORY_LOCKED = 0,
  REMANENCE_ERROR_CATEGORY_INVALID_IMAGE = 1,
  REMANENCE_ERROR_CATEGORY_UNSUPPORTED = 2,
  REMANENCE_ERROR_CATEGORY_READ_ONLY = 3,
  REMANENCE_ERROR_CATEGORY_NOT_FOUND = 4,
  REMANENCE_ERROR_CATEGORY_NOT_DIRECTORY = 5,
  REMANENCE_ERROR_CATEGORY_IS_DIRECTORY = 6,
  REMANENCE_ERROR_CATEGORY_NO_SPACE = 7,
  REMANENCE_ERROR_CATEGORY_IO = 8,
} RemanenceErrorCategory;

// What role a detected container plays in the image's layering.
typedef enum {
  REMANENCE_CONTAINER_KIND_ARCHIVE,
  REMANENCE_CONTAINER_KIND_IMAGE,
  REMANENCE_CONTAINER_KIND_PHYSICAL_MEDIA,
  REMANENCE_CONTAINER_KIND_FILESYSTEM,
  REMANENCE_CONTAINER_KIND_UNKNOWN,
} RemanenceContainerKind;

// Which layout details a container carries.
typedef enum {
  REMANENCE_LAYOUT_KIND_UNKNOWN,
  REMANENCE_LAYOUT_KIND_ARCHIVE,
  REMANENCE_LAYOUT_KIND_IMAGE,
  REMANENCE_LAYOUT_KIND_PHYSICAL_MEDIA,
  REMANENCE_LAYOUT_KIND_FILESYSTEM,
} RemanenceLayoutKind;

// Sector arrangement across a disk.
typedef enum {
  REMANENCE_SECTOR_LAYOUT_KIND_UNKNOWN,
  REMANENCE_SECTOR_LAYOUT_KIND_FIXED,
  REMANENCE_SECTOR_LAYOUT_KIND_VARIABLE,
} RemanenceSectorLayoutKind;

// The caller's declared intent when opening a disk (P7).
typedef enum {
  REMANENCE_ACCESS_INTENT_READ,
  REMANENCE_ACCESS_INTENT_WRITE,
} RemanenceAccessIntent;

// A session's access mode. For a disk this echoes the declared intent;
// for an identification session it reports what the P7 ladder obtained.
typedef enum {
  REMANENCE_ACCESS_MODE_READ_WRITE,
  REMANENCE_ACCESS_MODE_READ_ONLY,
} RemanenceAccessMode;

// The container format a disk image turned out to be.
typedef enum {
  REMANENCE_DISK_FORMAT_RAW,
  REMANENCE_DISK_FORMAT_QCOW2,
} RemanenceDiskFormat;

// What a FAT directory entry is.
typedef enum {
  REMANENCE_FAT_ENTRY_KIND_FILE,
  REMANENCE_FAT_ENTRY_KIND_DIRECTORY,
} RemanenceFatEntryKind;

// What to do with a location whose content its neighbour also holds.
typedef enum {
  // Take the profile's declaration, which for a 1541 refuses.
  REMANENCE_DUPLICATE_POLICY_DECLARED = 0,
  REMANENCE_DUPLICATE_POLICY_ADMIT_AS_OBSERVED = 1,
  REMANENCE_DUPLICATE_POLICY_OMIT = 2,
} RemanenceDuplicatePolicy;

// What a projection does with two transitions landing on one cycle.
typedef enum {
  REMANENCE_PROJECTION_POLICY_REFUSE = 0,
  REMANENCE_PROJECTION_POLICY_DECLARE_LOSS = 1,
} RemanenceProjectionPolicy;

// How the selected evidence becomes pulse strength.
typedef enum {
  // Every pulse carries `strength_state`; disagreement across the
  // unselected observations is declared loss rather than expressed.
  REMANENCE_PULSE_STRENGTH_POLICY_DECLARED = 0,
  // A pulse every observation places within `strength_window_cycles`
  // is strong; one only some corroborate is weak.
  REMANENCE_PULSE_STRENGTH_POLICY_FROM_AGREEMENT = 1,
} RemanencePulseStrengthPolicy;

// Where the medium's circle begins.
typedef enum {
  // The track's own seam, which is what the profile declares.
  REMANENCE_ORIGIN_POLICY_DECLARED = 0,
  // The angle in `origin_cycles`, stated outright by the caller.
  REMANENCE_ORIGIN_POLICY_ANGLE = 1,
} RemanenceOriginPolicy;

// An open archive listing, holding the claim on its file.
typedef struct RemanenceArchive RemanenceArchive;

// An open capture set, holding the claim on its archive.
typedef struct RemanenceCaptureSet RemanenceCaptureSet;

// An open disk image.
typedef struct RemanenceDisk RemanenceDisk;

// A snapshot of a disk's complete report (U4): blank is an
// answer, and every declared partition row stays, issues and all.
typedef struct RemanenceDiskGeometry RemanenceDiskGeometry;

// A directory listing.
typedef struct RemanenceFatEntryList RemanenceFatEntryList;

// Bytes read out of a volume or catalog.
typedef struct RemanenceFileData RemanenceFileData;

// A parsed HDOS directory listing.
typedef struct RemanenceHdosFileList RemanenceHdosFileList;

// The result of identifying a session's image.
typedef struct RemanenceIdentification RemanenceIdentification;

// A mastered medium, held in the session.
typedef struct RemanenceMasteredMedium RemanenceMasteredMedium;

// A planned reduction: everything computed, nothing written.
typedef struct RemanenceMasteringPlan RemanenceMasteringPlan;

// An opened P64 image, holding its claim on the file and the medium it
// decoded into private session storage.
typedef struct RemanenceP64Image RemanenceP64Image;

// What a container carried, or will carry, of one mastered medium.
typedef struct RemanenceP64Report RemanenceP64Report;

// A recognition result, ranked highest confidence first.
typedef struct RemanenceRecognition RemanenceRecognition;

// An open analysis session over one disk image.
typedef struct RemanenceSession RemanenceSession;

// One zone as a profile declares it, and what the capture recovered of
// it.
typedef struct {
  uint64_t first_location;
  uint64_t last_location;
  // What the family claims one location in this zone holds.
  uint32_t records_declared;
  uint64_t locations_declared;
  uint64_t locations_claimed;
  // The cell this zone claims, in thousandths of a reference cycle.
  uint64_t nominal_cell_millicycles;
} RemanenceZoneClaim;

// What the probe found at one source position. Every `has_*` flag says
// whether the value beside it was established at all: an absence is a
// finding, not a zero.
typedef struct {
  uint64_t position_numerator;
  uint64_t position_denominator;
  bool has_head;
  uint64_t head;
  // The family location this position addresses, where the family's
  // addressing covers it at all.
  bool has_family_location;
  uint64_t family_location;
  bool has_zone;
  uint32_t zone;
  uint32_t records;
  // The bit distance between record starts, where it repeats.
  bool has_record_bits;
  uint64_t record_bits;
  // How far that spacing departs from its own median. Zero is a
  // spacing that repeats to the bit.
  uint64_t record_bits_deviation;
  // The one departure from it, as an angle in reference-clock cycles.
  bool has_seam;
  uint64_t seam_cycles;
  // The derived cell projected onto the family's nominal rotation,
  // in thousandths of a reference cycle, beside what the zone claims.
  bool has_cell;
  uint64_t cell_millicycles;
  bool has_nominal_cell;
  uint64_t nominal_cell_millicycles;
  // How much of the interval population classified, per thousand.
  uint32_t resolved_permille;
  uint32_t observations;
  uint32_t observations_agreeing;
  // The adjacent position holding the same content, where one does.
  bool has_duplicate;
  uint64_t duplicate_numerator;
  uint64_t duplicate_denominator;
  bool claimed;
} RemanenceLocationVerdict;

// The complete declared policy for one reduction. There is no default:
// every field is a decision about evidence, and a reduction no input
// names is a refusal.
typedef struct {
  // The captured head supplying the family's one recorded surface.
  uint64_t side;
  // Which observation of each location is used.
  uint64_t observation_ordinal;
  RemanenceDuplicatePolicy duplicate;
  RemanenceProjectionPolicy projection;
  RemanencePulseStrengthPolicy pulse_strength;
  uint32_t strength_state;
  uint64_t strength_window_cycles;
  RemanenceOriginPolicy origin;
  uint64_t origin_cycles;
  // What makes any stochastic element reproducible.
  uint64_t seed;
} RemanenceMasteringPolicy;

// One half-track the medium will hold.
typedef struct {
  uint64_t source_position_numerator;
  uint64_t source_position_denominator;
  uint64_t half_track_numerator;
  uint64_t half_track_denominator;
  uint64_t observation_ordinal;
  uint64_t pulses;
  uint64_t strong_pulses;
  uint64_t weak_pulses;
  uint64_t origin_cycles;
  bool has_seam;
  uint64_t seam_cycles;
} RemanenceMasteredLocation;

// One half-track a P64 holds, in the container's addressing and the
// family's both.
typedef struct {
  // The container's own index byte, side bit included.
  uint8_t index;
  uint64_t side;
  uint64_t half_track_numerator;
  uint64_t half_track_denominator;
  uint64_t pulses;
  // Pulses that always trigger, that sometimes do, and that never do.
  uint64_t strong_pulses;
  uint64_t weak_pulses;
  uint64_t absent_pulses;
} RemanenceP64HalfTrack;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

// Returns the library version as a static string. Do not free.
const char *remanence_version(void);

// The stated default session cache bound, in bytes: what an open
// without a declared bound uses.
uint64_t remanence_default_cache_bytes(void);

// Frees a string returned through an `error_out` parameter.
void remanence_string_free(char *string);

// Opens `path` (UTF-8) — a raw disk image, or `archive[/entry]` naming an
// entry inside a supported archive (`.zip`, `.7z`) — with the built-in
// format adapters. Returns null on failure and stores a message in
// `error_out` (free with `remanence_string_free`).
RemanenceSession *remanence_session_open(const char *path,
                                         RemanenceErrorCategory *error_category_out,
                                         char **error_out);

// Opens a session as `remanence_session_open` does, under a declared
// session cache bound: at most `cache_bytes` stays resident, rounded
// up to whole 64 KiB extents with one extent as the floor.
RemanenceSession *remanence_session_open_with_cache(const char *path,
                                                    uint64_t cache_bytes,
                                                    RemanenceErrorCategory *error_category_out,
                                                    char **error_out);

// Frees a session handle.
void remanence_session_free(RemanenceSession *session);

// The path the session was opened from (the archive path for archive inputs).
const char *remanence_session_path(const RemanenceSession *session);

// The resolved image path (the entry name for archive inputs).
const char *remanence_session_image_path(const RemanenceSession *session);

// The resolved image's size in bytes.
uint64_t remanence_session_size_bytes(const RemanenceSession *session);

// Reads `length` bytes of the resolved image at `offset` into
// `buffer_out` — the bounded access form: the image streams from its
// backing and is never resident whole. Returns false on failure and
// stores a message in `error_out` (free with `remanence_string_free`).
bool remanence_session_read_at(const RemanenceSession *session,
                               uint64_t offset,
                               uint8_t *buffer_out,
                               size_t length,
                               RemanenceErrorCategory *error_category_out,
                               char **error_out);

// Whether the session has unsaved modifications.
bool remanence_session_is_modified(const RemanenceSession *session);

// Identifies the image's container layers and probable filesystem. Free the
// result with `remanence_identification_free`.
RemanenceIdentification *remanence_session_identify(const RemanenceSession *session);

// Frees an identification handle.
void remanence_identification_free(RemanenceIdentification *identification);

// Whether the session reported unsaved modifications at identify time.
bool remanence_identification_modified(const RemanenceIdentification *identification);

// Number of detected container layers.
size_t remanence_identification_container_count(const RemanenceIdentification *identification);

// Number of evidence lines.
size_t remanence_identification_evidence_count(const RemanenceIdentification *identification);

// One evidence line, or null when out of range.
const char *remanence_identification_evidence(const RemanenceIdentification *identification,
                                              size_t index);

// The container's kind, or `RemanenceContainerKind::Unknown` when out of range.
RemanenceContainerKind remanence_container_kind(const RemanenceIdentification *identification,
                                                size_t index);

// The container's id (e.g. "h8d", "zip", "hdos").
const char *remanence_container_id(const RemanenceIdentification *identification, size_t index);

// The container's human-readable name.
const char *remanence_container_name(const RemanenceIdentification *identification, size_t index);

// Detection confidence, 0-100.
uint8_t remanence_container_confidence(const RemanenceIdentification *identification, size_t index);

// Whether the container matched a known format.
bool remanence_container_known(const RemanenceIdentification *identification, size_t index);

// Current size in bytes; returns false when unknown.
bool remanence_container_current_bytes(const RemanenceIdentification *identification,
                                       size_t index,
                                       uint64_t *out);

// Expected size in bytes; returns false when unknown.
bool remanence_container_expected_bytes(const RemanenceIdentification *identification,
                                        size_t index,
                                        uint64_t *out);

// Which layout details this container carries.
RemanenceLayoutKind remanence_container_layout_kind(const RemanenceIdentification *identification,
                                                    size_t index);

// Archive layout: the archive file path; null for other layouts.
const char *remanence_container_archive_path(const RemanenceIdentification *identification,
                                             size_t index);

// Archive layout: the entry name inside the archive; null for other layouts.
const char *remanence_container_archive_entry_name(const RemanenceIdentification *identification,
                                                   size_t index);

// Archive layout: compressed entry size; returns false when unknown.
bool remanence_container_archive_compressed_size(const RemanenceIdentification *identification,
                                                 size_t index,
                                                 uint64_t *out);

// Archive layout: uncompressed entry size; returns false when unknown.
bool remanence_container_archive_uncompressed_size(const RemanenceIdentification *identification,
                                                   size_t index,
                                                   uint64_t *out);

// Image layout: payload offset in bytes; returns false when unknown.
bool remanence_container_image_payload_offset(const RemanenceIdentification *identification,
                                              size_t index,
                                              uint64_t *out);

// Image layout: payload length in bytes; returns false when unknown.
bool remanence_container_image_payload_length(const RemanenceIdentification *identification,
                                              size_t index,
                                              uint64_t *out);

// Physical media layout: whether disk geometry is known.
bool remanence_container_has_disk_layout(const RemanenceIdentification *identification,
                                         size_t index);

// Disk layout: media kind (e.g. "floppy"); null when unknown.
const char *remanence_container_disk_media_kind(const RemanenceIdentification *identification,
                                                size_t index);

// Disk layout: sector size in bytes; returns false when unknown.
bool remanence_container_disk_sector_size(const RemanenceIdentification *identification,
                                          size_t index,
                                          uint64_t *out);

// Disk layout: cylinder count; returns false when unknown.
bool remanence_container_disk_cylinders(const RemanenceIdentification *identification,
                                        size_t index,
                                        uint32_t *out);

// Disk layout: side count; returns false when unknown.
bool remanence_container_disk_sides(const RemanenceIdentification *identification,
                                    size_t index,
                                    uint32_t *out);

// Disk layout: how sectors are arranged.
RemanenceSectorLayoutKind remanence_container_disk_sector_layout_kind(const RemanenceIdentification *identification,
                                                                      size_t index);

// Disk layout: sectors per track for fixed layouts; 0 otherwise.
uint32_t remanence_container_disk_sectors_per_track(const RemanenceIdentification *identification,
                                                    size_t index);

// Disk layout: per-track entry count for variable layouts; 0 otherwise.
size_t remanence_container_disk_track_count(const RemanenceIdentification *identification,
                                            size_t index);

// Disk layout: one per-track entry for variable layouts. Returns false when
// out of range. `has_sector_size` and `sector_size` report the optional
// per-track sector size.
bool remanence_container_disk_track(const RemanenceIdentification *identification,
                                    size_t index,
                                    size_t track_index,
                                    uint32_t *cylinder,
                                    uint32_t *side,
                                    uint32_t *sectors,
                                    bool *has_sector_size,
                                    uint64_t *sector_size);

// Disk layout: total sector count; returns false when unknown.
bool remanence_container_disk_total_sectors(const RemanenceIdentification *identification,
                                            size_t index,
                                            uint64_t *out);

// Filesystem layout: offset in bytes; returns false when unknown.
bool remanence_container_fs_offset_bytes(const RemanenceIdentification *identification,
                                         size_t index,
                                         uint64_t *out);

// Filesystem layout: length in bytes; returns false when unknown.
bool remanence_container_fs_length_bytes(const RemanenceIdentification *identification,
                                         size_t index,
                                         uint64_t *out);

// Parses the HDOS directory from raw image bytes. Returns null on failure and
// stores a message in `error_out` (free with `remanence_string_free`).
RemanenceHdosFileList *remanence_list_hdos_files(const uint8_t *bytes,
                                                 size_t length,
                                                 RemanenceErrorCategory *error_category_out,
                                                 char **error_out);

// Parses the HDOS directory from a session's image. Returns null on
// failure and stores a message in `error_out` (free with `remanence_string_free`).
RemanenceHdosFileList *remanence_session_list_hdos_files(const RemanenceSession *session,
                                                         RemanenceErrorCategory *error_category_out,
                                                         char **error_out);

// Frees an HDOS file list handle.
void remanence_hdos_file_list_free(RemanenceHdosFileList *list);

// Number of files in the listing.
size_t remanence_hdos_file_count(const RemanenceHdosFileList *list);

// File name without extension, e.g. "HDOS".
const char *remanence_hdos_file_name(const RemanenceHdosFileList *list, size_t index);

// File extension, possibly empty, e.g. "SYS".
const char *remanence_hdos_file_extension(const RemanenceHdosFileList *list, size_t index);

// `"NAME.EXT"`, or `"NAME"` when the extension is empty.
const char *remanence_hdos_file_display_name(const RemanenceHdosFileList *list, size_t index);

// Size in 256-byte sectors.
uint32_t remanence_hdos_file_size_sectors(const RemanenceHdosFileList *list, size_t index);

// Size in bytes.
uint64_t remanence_hdos_file_size_bytes(const RemanenceHdosFileList *list, size_t index);

// Raw HDOS date word.
uint16_t remanence_hdos_file_modified_date_raw(const RemanenceHdosFileList *list, size_t index);

// Raw HDOS flag byte.
uint8_t remanence_hdos_file_flags_raw(const RemanenceHdosFileList *list, size_t index);

// HDOS flag letters (subset of "SLWC"), possibly empty.
const char *remanence_hdos_file_flags(const RemanenceHdosFileList *list, size_t index);

// HDOS catalog date, e.g. "09-May-78", or "No-Date".
const char *remanence_hdos_file_modified_date(const RemanenceHdosFileList *list, size_t index);

// Opens `path` (UTF-8) as a disk image — raw or qcow2, detected by
// magic — with the caller's declared intent (P7). A `Write` open
// claims the image exclusively for the session's whole life and fails
// at the open, naming the reason, when the claim cannot be secured —
// never by falling back; a `Read` open takes read access only, denies
// writes to others, and admits other readers. An interrupted commit
// left by an earlier session is reconciled before the disk is exposed
// (P9): the image comes back wholly the old state or wholly the
// committed new one, never a partial third state. Returns null on
// failure with a message in `error_out`.
RemanenceDisk *remanence_disk_open(const char *path,
                                   RemanenceAccessIntent intent,
                                   RemanenceErrorCategory *error_category_out,
                                   char **error_out);

// Opens a disk as `remanence_disk_open` does, under a declared session
// cache bound: at most `cache_bytes` of session state stays resident,
// rounded up to whole 64 KiB extents with one extent as the floor;
// altered state past the bound spills to private session storage,
// never the image.
RemanenceDisk *remanence_disk_open_with_cache(const char *path,
                                              RemanenceAccessIntent intent,
                                              uint64_t cache_bytes,
                                              RemanenceErrorCategory *error_category_out,
                                              char **error_out);

// Frees a disk handle, releasing the P7 claim. Uncommitted changes are
// discarded (the commit point never reached the file).
void remanence_disk_free(RemanenceDisk *disk);

// The disk session's access mode — an echo of the declared intent.
RemanenceAccessMode remanence_disk_mode(const RemanenceDisk *disk);

// The detected container format.
RemanenceDiskFormat remanence_disk_format(const RemanenceDisk *disk);

// The qcow2 version, or 0 for a raw image.
uint32_t remanence_disk_qcow2_version(const RemanenceDisk *disk);

// The virtual disk size in bytes.
uint64_t remanence_disk_size(const RemanenceDisk *disk);

// Whether uncommitted changes exist.
bool remanence_disk_is_modified(const RemanenceDisk *disk);

// Reads the disk's complete report (U4): its partitions and
// volumes as they actually are. Blank is an answer (zero volumes, see
// `remanence_geometry_is_blank`), a partition row the library cannot read
// stays in the report carrying its issue, and non-zero data that is
// neither a supported filesystem nor a partition table fails by name,
// kept distinct from blank. Free the result with
// `remanence_disk_geometry_free`.
RemanenceDiskGeometry *remanence_disk_geometry(RemanenceDisk *disk,
                                               RemanenceErrorCategory *error_category_out,
                                               char **error_out);

// Frees a geometry snapshot.
void remanence_disk_geometry_free(RemanenceDiskGeometry *geometry);

// Whether sector 0 was all zero: a blank disk with zero volumes — an
// answer, not an error.
bool remanence_geometry_is_blank(const RemanenceDiskGeometry *geometry);

// Number of partitions (0 for a partitionless image).
size_t remanence_geometry_partition_count(const RemanenceDiskGeometry *geometry);

// A partition's 1-based number.
uint32_t remanence_geometry_partition_number(const RemanenceDiskGeometry *geometry, size_t index);

// A partition's MBR type byte.
uint8_t remanence_geometry_partition_type_byte(const RemanenceDiskGeometry *geometry, size_t index);

// A partition row's kind: "primary" (an MBR slot, the extended
// container included) or "logical" (a row of the extended chain).
const char *remanence_geometry_partition_kind(const RemanenceDiskGeometry *geometry, size_t index);

// A partition's pinned type name, or null when the type byte is outside
// the claim — the row's issue then names the refusal.
const char *remanence_geometry_partition_type_name(const RemanenceDiskGeometry *geometry,
                                                   size_t index);

// A partition's start offset in bytes.
uint64_t remanence_geometry_partition_start_bytes(const RemanenceDiskGeometry *geometry,
                                                  size_t index);

// A partition's length in bytes.
uint64_t remanence_geometry_partition_length_bytes(const RemanenceDiskGeometry *geometry,
                                                   size_t index);

// Stores a partition row's issue category and returns true; returns
// false when the row was read cleanly (or the index is out of range).
// A row carrying an issue stays in the report with no volume read from
// it, and the rows behind it never renumber (U4).
bool remanence_geometry_partition_issue_category(const RemanenceDiskGeometry *geometry,
                                                 size_t index,
                                                 RemanenceErrorCategory *category_out);

// A partition row's issue diagnostic — why no volume was read from the
// row — or null when the row was read cleanly.
const char *remanence_geometry_partition_issue(const RemanenceDiskGeometry *geometry, size_t index);

// Number of volumes actually read (one guest drive letter each).
size_t remanence_geometry_volume_count(const RemanenceDiskGeometry *geometry);

// A volume's opaque stable identifier. The borrowed string is owned by
// `geometry`.
const char *remanence_geometry_volume_id(const RemanenceDiskGeometry *geometry, size_t index);

// The 1-based partition number a volume sits in; returns false for a
// partitionless image.
bool remanence_geometry_volume_partition_number(const RemanenceDiskGeometry *geometry,
                                                size_t index,
                                                uint32_t *out);

// The volume's FAT kind name ("FAT12" or "FAT16").
const char *remanence_geometry_volume_kind(const RemanenceDiskGeometry *geometry, size_t index);

// The volume label, or null when it has none.
const char *remanence_geometry_volume_label(const RemanenceDiskGeometry *geometry, size_t index);

// The volume's offset in bytes.
uint64_t remanence_geometry_volume_offset_bytes(const RemanenceDiskGeometry *geometry,
                                                size_t index);

// The volume's length in bytes.
uint64_t remanence_geometry_volume_length_bytes(const RemanenceDiskGeometry *geometry,
                                                size_t index);

// The volume's cluster size in bytes.
uint64_t remanence_geometry_volume_cluster_bytes(const RemanenceDiskGeometry *geometry,
                                                 size_t index);

// The volume's data-cluster count.
uint64_t remanence_geometry_volume_cluster_count(const RemanenceDiskGeometry *geometry,
                                                 size_t index);

// The BPB-stated sectors per track; returns false where the boot record
// states none.
bool remanence_geometry_volume_sectors_per_track(const RemanenceDiskGeometry *geometry,
                                                 size_t index,
                                                 uint32_t *out);

// The BPB-stated head count; returns false where the boot record states
// none.
bool remanence_geometry_volume_heads(const RemanenceDiskGeometry *geometry,
                                     size_t index,
                                     uint32_t *out);

// The volume's cylinder count, only where an exact derivation exists —
// the boot record's track geometry divides the total sector count with
// no remainder; returns false otherwise, never an invented value
// (U4).
bool remanence_geometry_volume_cylinders(const RemanenceDiskGeometry *geometry,
                                         size_t index,
                                         uint64_t *out);

// Lists a directory in `volume_id` ("" = root, "A/B" descends). Free
// with `remanence_fat_entry_list_free`.
RemanenceFatEntryList *remanence_disk_entries(RemanenceDisk *disk,
                                              const char *volume_id,
                                              const char *path,
                                              RemanenceErrorCategory *error_category_out,
                                              char **error_out);

// Answers one path in `volume_id` (U3): a one-entry listing when
// something exists there, an empty listing when nothing does — a
// missing leaf, a missing parent, or a parent that is a file alike.
// Absence is an answer, distinguished from failure, which returns null
// with the error set. Free with `remanence_fat_entry_list_free`.
RemanenceFatEntryList *remanence_disk_stat(RemanenceDisk *disk,
                                           const char *volume_id,
                                           const char *path,
                                           RemanenceErrorCategory *error_category_out,
                                           char **error_out);

// Frees a directory listing.
void remanence_fat_entry_list_free(RemanenceFatEntryList *list);

// Number of entries in the listing.
size_t remanence_fat_entry_count(const RemanenceFatEntryList *list);

// An entry's 8.3 name.
const char *remanence_fat_entry_name(const RemanenceFatEntryList *list, size_t index);

// Whether an entry is a file or a directory.
RemanenceFatEntryKind remanence_fat_entry_kind(const RemanenceFatEntryList *list, size_t index);

// An entry's size in bytes (0 for directories).
uint64_t remanence_fat_entry_size_bytes(const RemanenceFatEntryList *list, size_t index);

// Copies a file's bytes out of `volume_id`. Free with
// `remanence_file_data_free`.
RemanenceFileData *remanence_disk_read_file(RemanenceDisk *disk,
                                            const char *volume_id,
                                            const char *path,
                                            RemanenceErrorCategory *error_category_out,
                                            char **error_out);

// Reads part of a file into `buffer_out` — the streamed form beside
// `remanence_disk_read_file`: exactly `length` bytes at `offset`,
// which must lie within the file.
bool remanence_disk_read_file_at(RemanenceDisk *disk,
                                 const char *volume_id,
                                 const char *path,
                                 uint64_t offset,
                                 uint8_t *buffer_out,
                                 size_t length,
                                 RemanenceErrorCategory *error_category_out,
                                 char **error_out);

// Sets a file's size, creating it when absent — with
// `remanence_disk_write_file_at`, the streamed replacement for
// `remanence_disk_write_file`. Buffered until commit.
bool remanence_disk_resize_file(RemanenceDisk *disk,
                                const char *volume_id,
                                const char *path,
                                uint64_t size,
                                RemanenceErrorCategory *error_category_out,
                                char **error_out);

// Writes part of a file in place — the streamed form beside
// `remanence_disk_write_file`: the span must lie within the file's
// current size. Buffered until commit.
bool remanence_disk_write_file_at(RemanenceDisk *disk,
                                  const char *volume_id,
                                  const char *path,
                                  uint64_t offset,
                                  const uint8_t *bytes,
                                  size_t length,
                                  RemanenceErrorCategory *error_category_out,
                                  char **error_out);

// The bytes of a read-out file; valid until the handle is freed.
const uint8_t *remanence_file_data_bytes(const RemanenceFileData *data, size_t *length_out);

// Frees read-out file bytes.
void remanence_file_data_free(RemanenceFileData *data);

// Writes a file into `volume_id`. An existing file is overwritten —
// shorter or longer, its old clusters released and reclaimed — while
// an existing directory is refused. Buffered until `remanence_disk_commit`.
bool remanence_disk_write_file(RemanenceDisk *disk,
                               const char *volume_id,
                               const char *path,
                               const uint8_t *bytes,
                               size_t length,
                               RemanenceErrorCategory *error_category_out,
                               char **error_out);

// Ensures a directory exists in `volume_id`: missing parents are
// created, and a path that already leads to a directory succeeds
// unchanged. Buffered until commit.
bool remanence_disk_make_directory(RemanenceDisk *disk,
                                   const char *volume_id,
                                   const char *path,
                                   RemanenceErrorCategory *error_category_out,
                                   char **error_out);

// The commit point (P2): everything buffered reaches the image, then a
// flush. Until this call, nothing has touched the file. The commit is
// durable (P9): a private recovery journal is armed before the first
// byte of the file changes, so an interruption at any point leaves
// state the next open reconciles to wholly the old image or wholly
// the committed new one.
bool remanence_disk_commit(RemanenceDisk *disk,
                           RemanenceErrorCategory *error_category_out,
                           char **error_out);

// Discards everything buffered; the image is untouched.
void remanence_disk_rollback(RemanenceDisk *disk);

// Which P7 mode the session's open obtained on its source file.
RemanenceAccessMode remanence_session_access_mode(const RemanenceSession *session);

// Reads a cataloged HDOS file's contents out of raw image bytes. Free
// with `remanence_file_data_free`.
RemanenceFileData *remanence_read_hdos_file(const uint8_t *bytes,
                                            size_t length,
                                            const char *name,
                                            RemanenceErrorCategory *error_category_out,
                                            char **error_out);

// Reads a cataloged HDOS file out of a session's image. Free with
// `remanence_file_data_free`.
RemanenceFileData *remanence_session_read_hdos_file(const RemanenceSession *session,
                                                    const char *name,
                                                    RemanenceErrorCategory *error_category_out,
                                                    char **error_out);

// Opens the archive at `path` (UTF-8) and reads its entry list. A path
// naming no archive format this library reads is refused by name.
// Returns null on failure and stores a message in `error_out` (free with
// `remanence_string_free`).
RemanenceArchive *remanence_archive_open(const char *path,
                                         RemanenceErrorCategory *error_category_out,
                                         char **error_out);

// Frees an archive handle, releasing its claim on the file.
void remanence_archive_free(RemanenceArchive *archive);

// The path the archive was opened from.
const char *remanence_archive_path(const RemanenceArchive *archive);

// The archive format's stable identifier, e.g. "zip" or "7z".
const char *remanence_archive_format_id(const RemanenceArchive *archive);

// The archive format's human-readable name.
const char *remanence_archive_format_name(const RemanenceArchive *archive);

// Which P7 mode the open obtained on the archive file.
RemanenceAccessMode remanence_archive_access_mode(const RemanenceArchive *archive);

// The archive file's own size in bytes.
uint64_t remanence_archive_size_bytes(const RemanenceArchive *archive);

// Number of entries the archive holds.
size_t remanence_archive_entry_count(const RemanenceArchive *archive);

// One entry's `/`-separated path inside the archive, or null when out
// of range.
const char *remanence_archive_entry_name(const RemanenceArchive *archive, size_t index);

// Whether the entry is a directory.
bool remanence_archive_entry_is_dir(const RemanenceArchive *archive, size_t index);

// The entry's size once decoded, as the archive declares it; 0 when out
// of range.
uint64_t remanence_archive_entry_uncompressed_size(const RemanenceArchive *archive, size_t index);

// The entry's packed size; returns false when the grammar attributes
// none to a single entry — a member of a solid 7z folder — or when the
// index is out of range.
bool remanence_archive_entry_compressed_size(const RemanenceArchive *archive,
                                             size_t index,
                                             uint64_t *out);

// Opens the KryoFlux capture set held by `path` (UTF-8) — an archive
// this library reads, optionally followed by the subtree inside it that
// holds the members — with the stated default session cache bound.
// An incomplete, duplicate, contradictory, or unrelated member refuses
// the whole set. Returns null on failure and stores a message in
// `error_out` (free with `remanence_string_free`).
RemanenceCaptureSet *remanence_capture_set_open(const char *path,
                                                RemanenceErrorCategory *error_category_out,
                                                char **error_out);

// Opens a capture set as `remanence_capture_set_open` does, under a
// declared cache bound: at most `cache_bytes` of the decoded capture
// stays resident. The bound narrows the working set; it never refuses
// service.
RemanenceCaptureSet *remanence_capture_set_open_with_cache(const char *path,
                                                           uint64_t cache_bytes,
                                                           RemanenceErrorCategory *error_category_out,
                                                           char **error_out);

// Frees a capture-set handle, releasing its claim on the archive and
// discarding the private session storage the capture decoded into.
void remanence_capture_set_free(RemanenceCaptureSet *set);

// The path the set was opened from.
const char *remanence_capture_set_path(const RemanenceCaptureSet *set);

// The subtree inside the archive the members were read from, or null
// when the whole archive is the set.
const char *remanence_capture_set_subtree(const RemanenceCaptureSet *set);

// The capture format's stable identifier, "kryoflux".
const char *remanence_capture_set_format_id(const RemanenceCaptureSet *set);

// The capture format's human-readable name.
const char *remanence_capture_set_format_name(const RemanenceCaptureSet *set);

// The archive grammar the members were read through, e.g. "7z".
const char *remanence_capture_set_archive_format_id(const RemanenceCaptureSet *set);

// Which P7 mode the open obtained on the archive file.
RemanenceAccessMode remanence_capture_set_access_mode(const RemanenceCaptureSet *set);

// The capture's declared timing basis, as an exact ratio of ticks per
// second. Returns false when the handle is null.
bool remanence_capture_set_ticks_per_second(const RemanenceCaptureSet *set,
                                            uint64_t *numerator_out,
                                            uint64_t *denominator_out);

// How many bytes of private session storage the decoded capture
// occupies.
uint64_t remanence_capture_set_backing_bytes(const RemanenceCaptureSet *set);

// How much of that backing is currently resident. The capture is never
// held whole.
uint64_t remanence_capture_set_resident_bytes(const RemanenceCaptureSet *set);

// Number of evidence lines behind the recognition.
size_t remanence_capture_set_evidence_count(const RemanenceCaptureSet *set);

// One evidence line, or null when out of range.
const char *remanence_capture_set_evidence(const RemanenceCaptureSet *set, size_t index);

// Number of members the set holds.
size_t remanence_capture_set_member_count(const RemanenceCaptureSet *set);

// One member's catalog identity, or null when out of range.
const char *remanence_capture_set_member_entry_name(const RemanenceCaptureSet *set, size_t member);

// One member's size in bytes as the catalog declares it; 0 when out of
// range.
uint64_t remanence_capture_set_member_entry_bytes(const RemanenceCaptureSet *set, size_t member);

// One member's drive-step position, as an exact ratio. Returns false
// when out of range.
bool remanence_capture_set_member_position(const RemanenceCaptureSet *set,
                                           size_t member,
                                           uint64_t *numerator_out,
                                           uint64_t *denominator_out);

// The head that captured this position; returns false when the source
// numbers no head, which is a different fact from head zero, or when
// the index is out of range.
bool remanence_capture_set_member_head(const RemanenceCaptureSet *set,
                                       size_t member,
                                       uint64_t *out);

// Number of things recorded as qualified about this member.
size_t remanence_capture_set_member_issue_count(const RemanenceCaptureSet *set, size_t member);

// One issue's stable code, or null when out of range.
const char *remanence_capture_set_member_issue_code(const RemanenceCaptureSet *set,
                                                    size_t member,
                                                    size_t issue);

// One issue's human-readable detail, or null when out of range.
const char *remanence_capture_set_member_issue_detail(const RemanenceCaptureSet *set,
                                                      size_t member,
                                                      size_t issue);

// Number of source transfers recorded at this member's location.
size_t remanence_capture_set_member_run_count(const RemanenceCaptureSet *set, size_t member);

// One run's place in the member's recorded order; 0 when out of range.
uint64_t remanence_capture_set_run_ordinal(const RemanenceCaptureSet *set,
                                           size_t member,
                                           size_t run);

// How many flux transitions the run recorded.
uint64_t remanence_capture_set_run_transitions(const RemanenceCaptureSet *set,
                                               size_t member,
                                               size_t run);

// The last transition's tick: the extent of what was recorded, not a
// circumference. A run states no period.
uint64_t remanence_capture_set_run_extent_ticks(const RemanenceCaptureSet *set,
                                                size_t member,
                                                size_t run);

// How many timed markers sit on channels parallel to the run's flux.
uint64_t remanence_capture_set_run_markers(const RemanenceCaptureSet *set,
                                           size_t member,
                                           size_t run);

// How many of those markers are index events.
uint64_t remanence_capture_set_run_index_markers(const RemanenceCaptureSet *set,
                                                 size_t member,
                                                 size_t run);

// The result the capture tool declared for this transfer, where it
// declared one; zero is a clean read. Returns false when it declared
// none or the index is out of range.
bool remanence_capture_set_run_transfer_result(const RemanenceCaptureSet *set,
                                               size_t member,
                                               size_t run,
                                               uint32_t *out);

// Transitions recorded before the run's first index: evidence that
// bounding into circular observations does not consume.
uint64_t remanence_capture_set_run_transitions_before_first_index(const RemanenceCaptureSet *set,
                                                                  size_t member,
                                                                  size_t run);

// Transitions recorded after the run's last index, on the same terms.
uint64_t remanence_capture_set_run_transitions_after_last_index(const RemanenceCaptureSet *set,
                                                                size_t member,
                                                                size_t run);

// How many circular observations the run's indices bounded.
size_t remanence_capture_set_run_observation_count(const RemanenceCaptureSet *set,
                                                   size_t member,
                                                   size_t run);

// One observation's place in the location's source-record order. Not a
// rank: nothing here says it is a good or complete revolution.
uint64_t remanence_capture_set_observation_ordinal(const RemanenceCaptureSet *set,
                                                   size_t member,
                                                   size_t run,
                                                   size_t observation);

// The observation's declared circumference, in the capture's own ticks.
uint64_t remanence_capture_set_observation_span_ticks(const RemanenceCaptureSet *set,
                                                      size_t member,
                                                      size_t run,
                                                      size_t observation);

// How many transitions the observation holds.
uint64_t remanence_capture_set_observation_transitions(const RemanenceCaptureSet *set,
                                                       size_t member,
                                                       size_t run,
                                                       size_t observation);

// How many markers the observation holds.
uint64_t remanence_capture_set_observation_markers(const RemanenceCaptureSet *set,
                                                   size_t member,
                                                   size_t run,
                                                   size_t observation);

// Recognizes the drive family a capture set was recorded under. Every
// enrolled profile is consulted and what claims the capture is ranked;
// a capture no profile claims is a named refusal. Returns null on
// failure and stores a message in `error_out` (free with
// `remanence_string_free`).
RemanenceRecognition *remanence_capture_set_recognize(const RemanenceCaptureSet *set,
                                                      RemanenceErrorCategory *error_category_out,
                                                      char **error_out);

// Recognizes the capture against one named profile, whether or not it
// would have won the ranking. A profile this build does not enroll is
// refused by name.
RemanenceRecognition *remanence_capture_set_recognize_as(const RemanenceCaptureSet *set,
                                                         const char *profile_id,
                                                         RemanenceErrorCategory *error_category_out,
                                                         char **error_out);

// Frees a recognition handle.
void remanence_recognition_free(RemanenceRecognition *recognition);

// The profile the caller pinned, or null when the ranking was open.
const char *remanence_recognition_pinned(const RemanenceRecognition *recognition);

// Number of evidence lines about the recognition itself.
size_t remanence_recognition_evidence_count(const RemanenceRecognition *recognition);

// One of those lines, or null when out of range.
const char *remanence_recognition_evidence(const RemanenceRecognition *recognition, size_t index);

// How many profiles claimed the capture, highest confidence first.
size_t remanence_recognition_verdict_count(const RemanenceRecognition *recognition);

// One verdict's profile identifier, or null when out of range.
const char *remanence_recognition_profile_id(const RemanenceRecognition *recognition,
                                             size_t verdict);

// One verdict's human-readable family name.
const char *remanence_recognition_profile_name(const RemanenceRecognition *recognition,
                                               size_t verdict);

// Detection confidence, 0-100. Never an answer on its own: read the
// evidence beside it.
uint8_t remanence_recognition_confidence(const RemanenceRecognition *recognition, size_t verdict);

// How many of the profile's declared locations the capture claimed,
// and how many it declares.
uint32_t remanence_recognition_locations_claimed(const RemanenceRecognition *recognition,
                                                 size_t verdict);

uint64_t remanence_recognition_locations_declared(const RemanenceRecognition *recognition,
                                                  size_t verdict);

// Number of evidence lines behind this verdict.
size_t remanence_recognition_verdict_evidence_count(const RemanenceRecognition *recognition,
                                                    size_t verdict);

// One of those lines, or null when out of range.
const char *remanence_recognition_verdict_evidence(const RemanenceRecognition *recognition,
                                                   size_t verdict,
                                                   size_t index);

// How many density zones the profile declares.
size_t remanence_recognition_zone_count(const RemanenceRecognition *recognition, size_t verdict);

// One zone, written into `out`. Returns false when out of range.
bool remanence_recognition_zone(const RemanenceRecognition *recognition,
                                size_t verdict,
                                size_t zone,
                                RemanenceZoneClaim *out);

// How many source positions the probe accounted for.
size_t remanence_recognition_location_count(const RemanenceRecognition *recognition,
                                            size_t verdict);

// One position's findings, written into `out`. Returns false when out
// of range.
bool remanence_recognition_location(const RemanenceRecognition *recognition,
                                    size_t verdict,
                                    size_t location,
                                    RemanenceLocationVerdict *out);

// The member one position was read from, or null when out of range.
const char *remanence_recognition_location_artifact(const RemanenceRecognition *recognition,
                                                    size_t verdict,
                                                    size_t location);

// Why a position was not claimed, in the profile's own terms; null when
// it was claimed or the index is out of range.
const char *remanence_recognition_location_refusal(const RemanenceRecognition *recognition,
                                                   size_t verdict,
                                                   size_t location);

// Plans the reduction of a capture set to one 1541 flux medium.
// Nothing is written and nothing is mutated. Returns null on failure
// and stores a message in `error_out` (free with
// `remanence_string_free`).
RemanenceMasteringPlan *remanence_capture_set_plan_c1541_mastering(const RemanenceCaptureSet *set,
                                                                   const RemanenceMasteringPolicy *policy,
                                                                   RemanenceErrorCategory *error_category_out,
                                                                   char **error_out);

// Frees a plan handle.
void remanence_mastering_plan_free(RemanenceMasteringPlan *plan);

// Produces the medium the plan described, consuming the plan: the
// handle is freed whether this succeeds or fails, and must not be used
// again. Returns null on failure.
RemanenceMasteredMedium *remanence_mastering_plan_execute(RemanenceMasteringPlan *plan,
                                                          uint64_t cache_bytes,
                                                          RemanenceErrorCategory *error_category_out,
                                                          char **error_out);

// Frees a mastered-medium handle, discarding its private session
// storage.
void remanence_mastered_medium_free(RemanenceMasteredMedium *medium);

// How many locations the medium claims.
uint64_t remanence_mastered_medium_locations(const RemanenceMasteredMedium *medium);

// How many bytes of private session storage the medium occupies, and
// how much of that is currently resident.
uint64_t remanence_mastered_medium_backing_bytes(const RemanenceMasteredMedium *medium);

uint64_t remanence_mastered_medium_resident_bytes(const RemanenceMasteredMedium *medium);

// The profile the reduction was declared by. Pass whichever handle you
// hold and null for the other.
const char *remanence_mastering_profile_id(const RemanenceMasteringPlan *plan,
                                           const RemanenceMasteredMedium *medium);

// The frame the medium is expressed in.
uint64_t remanence_mastering_reference_clock_hz(const RemanenceMasteringPlan *plan,
                                                const RemanenceMasteredMedium *medium);

uint64_t remanence_mastering_cycles_per_rotation(const RemanenceMasteringPlan *plan,
                                                 const RemanenceMasteredMedium *medium);

// Which rule placed the circle's origin.
const char *remanence_mastering_origin_rule(const RemanenceMasteringPlan *plan,
                                            const RemanenceMasteredMedium *medium);

// How many half-tracks the reduction produces.
size_t remanence_mastering_location_count(const RemanenceMasteringPlan *plan,
                                          const RemanenceMasteredMedium *medium);

// One of them, written into `out`. Returns false when out of range.
bool remanence_mastering_location(const RemanenceMasteringPlan *plan,
                                  const RemanenceMasteredMedium *medium,
                                  size_t index,
                                  RemanenceMasteredLocation *out);

// How many kinds of loss the destination will not carry.
size_t remanence_mastering_declared_loss_count(const RemanenceMasteringPlan *plan,
                                               const RemanenceMasteredMedium *medium);

// One loss entry's stable code, or null when out of range.
const char *remanence_mastering_declared_loss_code(const RemanenceMasteringPlan *plan,
                                                   const RemanenceMasteredMedium *medium,
                                                   size_t index);

// What was lost, in the source's own terms. A count is not an account.
const char *remanence_mastering_declared_loss_detail(const RemanenceMasteringPlan *plan,
                                                     const RemanenceMasteredMedium *medium,
                                                     size_t index);

// How much of it there was, in whatever the detail counts.
uint64_t remanence_mastering_declared_loss_amount(const RemanenceMasteringPlan *plan,
                                                  const RemanenceMasteredMedium *medium,
                                                  size_t index);

// The policy that produced the plan, stated in full.
size_t remanence_mastering_evidence_count(const RemanenceMasteringPlan *plan,
                                          const RemanenceMasteredMedium *medium);

const char *remanence_mastering_evidence(const RemanenceMasteringPlan *plan,
                                         const RemanenceMasteredMedium *medium,
                                         size_t index);

// Opens the P64 image at `path` (UTF-8), claiming the file and decoding
// every half-track once into private session storage. The version is
// checked before anything else is touched, and a version, flag bit, or
// chunk signature past this release's claim is refused by name. Returns
// null on failure and stores a message in `error_out` (free with
// `remanence_string_free`).
RemanenceP64Image *remanence_p64_image_open(const char *path,
                                            RemanenceErrorCategory *error_category_out,
                                            char **error_out);

// Opens a P64 image as `remanence_p64_image_open` does, under a
// declared cache bound: at most `cache_bytes` of the decoded medium
// stays resident. The bound narrows the working set; it never refuses
// service.
RemanenceP64Image *remanence_p64_image_open_with_cache(const char *path,
                                                       uint64_t cache_bytes,
                                                       RemanenceErrorCategory *error_category_out,
                                                       char **error_out);

// Frees an image handle, releasing its claim on the file and discarding
// the private session storage the medium decoded into.
void remanence_p64_image_free(RemanenceP64Image *image);

// The path the image was opened from.
const char *remanence_p64_image_path(const RemanenceP64Image *image);

// Which P7 mode the open obtained on the file.
RemanenceAccessMode remanence_p64_image_access_mode(const RemanenceP64Image *image);

// How many bytes of private session storage the decoded medium
// occupies, and how much of that is currently resident.
uint64_t remanence_p64_image_backing_bytes(const RemanenceP64Image *image);

uint64_t remanence_p64_image_resident_bytes(const RemanenceP64Image *image);

// Computes what a P64 will and will not carry of a mastered medium,
// writing nothing. Read it before writing: the write adds nothing to
// the account. Returns null on failure.
RemanenceP64Report *remanence_mastered_medium_describe_p64(const RemanenceMasteredMedium *medium,
                                                           RemanenceErrorCategory *error_category_out,
                                                           char **error_out);

// Writes a mastered medium into a new P64 image at `path` (UTF-8) and
// reports what the container carried. The medium is untouched, an
// existing destination is a named refusal rather than an overwrite, and
// an interruption leaves the destination absent rather than half an
// artifact. Returns null on failure.
RemanenceP64Report *remanence_mastered_medium_write_p64(const RemanenceMasteredMedium *medium,
                                                        const char *path,
                                                        RemanenceErrorCategory *error_category_out,
                                                        char **error_out);

// Frees a report handle.
void remanence_p64_report_free(RemanenceP64Report *report);

// The container format's stable identifier, "p64".
const char *remanence_p64_format_id(const RemanenceP64Image *image,
                                    const RemanenceP64Report *report);

const char *remanence_p64_format_name(const RemanenceP64Image *image,
                                      const RemanenceP64Report *report);

// The container's declared format version.
uint32_t remanence_p64_version(const RemanenceP64Image *image, const RemanenceP64Report *report);

bool remanence_p64_write_protected(const RemanenceP64Image *image,
                                   const RemanenceP64Report *report);

bool remanence_p64_double_sided(const RemanenceP64Image *image, const RemanenceP64Report *report);

// The drive profile the container's own signature names, and the frame
// that profile declares.
const char *remanence_p64_profile_id(const RemanenceP64Image *image,
                                     const RemanenceP64Report *report);

uint64_t remanence_p64_reference_clock_hz(const RemanenceP64Image *image,
                                          const RemanenceP64Report *report);

uint64_t remanence_p64_cycles_per_rotation(const RemanenceP64Image *image,
                                           const RemanenceP64Report *report);

// How many half-tracks the container holds.
size_t remanence_p64_half_track_count(const RemanenceP64Image *image,
                                      const RemanenceP64Report *report);

// One of them, written into `out`. Returns false when out of range.
bool remanence_p64_half_track(const RemanenceP64Image *image,
                              const RemanenceP64Report *report,
                              size_t index,
                              RemanenceP64HalfTrack *out);

// How many kinds of loss the crossing does not carry.
size_t remanence_p64_declared_loss_count(const RemanenceP64Image *image,
                                         const RemanenceP64Report *report);

// One loss entry's stable code, or null when out of range.
const char *remanence_p64_declared_loss_code(const RemanenceP64Image *image,
                                             const RemanenceP64Report *report,
                                             size_t index);

// What was lost, in the source's own terms. A count is not an account.
const char *remanence_p64_declared_loss_detail(const RemanenceP64Image *image,
                                               const RemanenceP64Report *report,
                                               size_t index);

// How much of it there was, in whatever the detail counts.
uint64_t remanence_p64_declared_loss_amount(const RemanenceP64Image *image,
                                            const RemanenceP64Report *report,
                                            size_t index);

// How the container was recognized and what this adapter claims of it.
size_t remanence_p64_evidence_count(const RemanenceP64Image *image,
                                    const RemanenceP64Report *report);

const char *remanence_p64_evidence(const RemanenceP64Image *image,
                                   const RemanenceP64Report *report,
                                   size_t index);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* REMANENCE_H */
