/*
 * SPDX-FileCopyrightText: 2026 Paul Galbraith
 * SPDX-License-Identifier: GPL-3.0-only
 */

#ifndef REMANENCE_H
#define REMANENCE_H

/* Generated by cbindgen from crates/remanence-ffi. Do not edit by hand. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

// What role a detected container plays in the image's layering.
typedef enum {
  RMN_CONTAINER_KIND_ARCHIVE,
  RMN_CONTAINER_KIND_IMAGE,
  RMN_CONTAINER_KIND_PHYSICAL_MEDIA,
  RMN_CONTAINER_KIND_FILESYSTEM,
  RMN_CONTAINER_KIND_UNKNOWN,
} RmnContainerKind;

// Which layout details a container carries.
typedef enum {
  RMN_LAYOUT_KIND_UNKNOWN,
  RMN_LAYOUT_KIND_ARCHIVE,
  RMN_LAYOUT_KIND_IMAGE,
  RMN_LAYOUT_KIND_PHYSICAL_MEDIA,
  RMN_LAYOUT_KIND_FILESYSTEM,
} RmnLayoutKind;

// Sector arrangement across a disk.
typedef enum {
  RMN_SECTOR_LAYOUT_KIND_UNKNOWN,
  RMN_SECTOR_LAYOUT_KIND_FIXED,
  RMN_SECTOR_LAYOUT_KIND_VARIABLE,
} RmnSectorLayoutKind;

// Which P7 mode an open obtained.
typedef enum {
  RMN_ACCESS_MODE_READ_WRITE,
  RMN_ACCESS_MODE_READ_ONLY,
} RmnAccessMode;

// The container format a disk image turned out to be.
typedef enum {
  RMN_DISK_FORMAT_RAW,
  RMN_DISK_FORMAT_QCOW2,
} RmnDiskFormat;

// What a FAT directory entry is.
typedef enum {
  RMN_FAT_ENTRY_KIND_FILE,
  RMN_FAT_ENTRY_KIND_DIRECTORY,
} RmnFatEntryKind;

// An open disk image.
typedef struct RmnDisk RmnDisk;

// A snapshot of a disk's partitions and volumes.
typedef struct RmnDiskGeometry RmnDiskGeometry;

// A directory listing.
typedef struct RmnFatEntryList RmnFatEntryList;

// Bytes read out of a volume or catalog.
typedef struct RmnFileData RmnFileData;

// A parsed HDOS directory listing.
typedef struct RmnHdosFileList RmnHdosFileList;

// The result of identifying a session's image.
typedef struct RmnIdentification RmnIdentification;

// An open analysis session over one disk image.
typedef struct RmnSession RmnSession;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

// Returns the library version as a static string. Do not free.
const char *rmn_version(void);

// Frees a string returned through an `error_out` parameter.
void rmn_string_free(char *string);

// Opens `path` (UTF-8) — a raw disk image, or `archive.zip[/entry]` — with
// the default format registry. Returns null on failure and stores a message
// in `error_out` (free with `rmn_string_free`).
RmnSession *rmn_session_open(const char *path, char **error_out);

// Frees a session handle.
void rmn_session_free(RmnSession *session);

// The path the session was opened from (the archive path for ZIP inputs).
const char *rmn_session_path(const RmnSession *session);

// The resolved image path (the entry name for ZIP inputs).
const char *rmn_session_image_path(const RmnSession *session);

// The resolved image bytes; valid until the session is freed.
const uint8_t *rmn_session_bytes(const RmnSession *session, size_t *length_out);

// Whether the session has unsaved modifications.
bool rmn_session_is_modified(const RmnSession *session);

// Identifies the image's container layers and probable filesystem. Free the
// result with `rmn_identification_free`.
RmnIdentification *rmn_session_identify(const RmnSession *session);

// Frees an identification handle.
void rmn_identification_free(RmnIdentification *identification);

// Whether the session reported unsaved modifications at identify time.
bool rmn_identification_modified(const RmnIdentification *identification);

// Number of detected container layers.
size_t rmn_identification_container_count(const RmnIdentification *identification);

// Number of evidence lines.
size_t rmn_identification_evidence_count(const RmnIdentification *identification);

// One evidence line, or null when out of range.
const char *rmn_identification_evidence(const RmnIdentification *identification, size_t index);

// The container's kind, or `RmnContainerKind::Unknown` when out of range.
RmnContainerKind rmn_container_kind(const RmnIdentification *identification, size_t index);

// The container's id (e.g. "h8d", "zip", "hdos").
const char *rmn_container_id(const RmnIdentification *identification, size_t index);

// The container's human-readable name.
const char *rmn_container_name(const RmnIdentification *identification, size_t index);

// Detection confidence, 0-100.
uint8_t rmn_container_confidence(const RmnIdentification *identification, size_t index);

// Whether the container matched a known format.
bool rmn_container_known(const RmnIdentification *identification, size_t index);

// Current size in bytes; returns false when unknown.
bool rmn_container_current_bytes(const RmnIdentification *identification,
                                 size_t index,
                                 uint64_t *out);

// Expected size in bytes; returns false when unknown.
bool rmn_container_expected_bytes(const RmnIdentification *identification,
                                  size_t index,
                                  uint64_t *out);

// Which layout details this container carries.
RmnLayoutKind rmn_container_layout_kind(const RmnIdentification *identification, size_t index);

// Archive layout: the archive file path; null for other layouts.
const char *rmn_container_archive_path(const RmnIdentification *identification, size_t index);

// Archive layout: the entry name inside the archive; null for other layouts.
const char *rmn_container_archive_entry_name(const RmnIdentification *identification, size_t index);

// Archive layout: compressed entry size; returns false when unknown.
bool rmn_container_archive_compressed_size(const RmnIdentification *identification,
                                           size_t index,
                                           uint64_t *out);

// Archive layout: uncompressed entry size; returns false when unknown.
bool rmn_container_archive_uncompressed_size(const RmnIdentification *identification,
                                             size_t index,
                                             uint64_t *out);

// Image layout: payload offset in bytes; returns false when unknown.
bool rmn_container_image_payload_offset(const RmnIdentification *identification,
                                        size_t index,
                                        uint64_t *out);

// Image layout: payload length in bytes; returns false when unknown.
bool rmn_container_image_payload_length(const RmnIdentification *identification,
                                        size_t index,
                                        uint64_t *out);

// Physical media layout: whether disk geometry is known.
bool rmn_container_has_disk_layout(const RmnIdentification *identification, size_t index);

// Disk layout: media kind (e.g. "floppy"); null when unknown.
const char *rmn_container_disk_media_kind(const RmnIdentification *identification, size_t index);

// Disk layout: sector size in bytes; returns false when unknown.
bool rmn_container_disk_sector_size(const RmnIdentification *identification,
                                    size_t index,
                                    uint64_t *out);

// Disk layout: cylinder count; returns false when unknown.
bool rmn_container_disk_cylinders(const RmnIdentification *identification,
                                  size_t index,
                                  uint32_t *out);

// Disk layout: side count; returns false when unknown.
bool rmn_container_disk_sides(const RmnIdentification *identification, size_t index, uint32_t *out);

// Disk layout: how sectors are arranged.
RmnSectorLayoutKind rmn_container_disk_sector_layout_kind(const RmnIdentification *identification,
                                                          size_t index);

// Disk layout: sectors per track for fixed layouts; 0 otherwise.
uint32_t rmn_container_disk_sectors_per_track(const RmnIdentification *identification,
                                              size_t index);

// Disk layout: per-track entry count for variable layouts; 0 otherwise.
size_t rmn_container_disk_track_count(const RmnIdentification *identification, size_t index);

// Disk layout: one per-track entry for variable layouts. Returns false when
// out of range. `has_sector_size` and `sector_size` report the optional
// per-track sector size.
bool rmn_container_disk_track(const RmnIdentification *identification,
                              size_t index,
                              size_t track_index,
                              uint32_t *cylinder,
                              uint32_t *side,
                              uint32_t *sectors,
                              bool *has_sector_size,
                              uint64_t *sector_size);

// Disk layout: total sector count; returns false when unknown.
bool rmn_container_disk_total_sectors(const RmnIdentification *identification,
                                      size_t index,
                                      uint64_t *out);

// Filesystem layout: offset in bytes; returns false when unknown.
bool rmn_container_fs_offset_bytes(const RmnIdentification *identification,
                                   size_t index,
                                   uint64_t *out);

// Filesystem layout: length in bytes; returns false when unknown.
bool rmn_container_fs_length_bytes(const RmnIdentification *identification,
                                   size_t index,
                                   uint64_t *out);

// Parses the HDOS directory from raw image bytes. Returns null on failure and
// stores a message in `error_out` (free with `rmn_string_free`).
RmnHdosFileList *rmn_list_hdos_files(const uint8_t *bytes, size_t length, char **error_out);

// Parses the HDOS directory from a session's image bytes. Returns null on
// failure and stores a message in `error_out` (free with `rmn_string_free`).
RmnHdosFileList *rmn_session_list_hdos_files(const RmnSession *session, char **error_out);

// Frees an HDOS file list handle.
void rmn_hdos_file_list_free(RmnHdosFileList *list);

// Number of files in the listing.
size_t rmn_hdos_file_count(const RmnHdosFileList *list);

// File name without extension, e.g. "HDOS".
const char *rmn_hdos_file_name(const RmnHdosFileList *list, size_t index);

// File extension, possibly empty, e.g. "SYS".
const char *rmn_hdos_file_extension(const RmnHdosFileList *list, size_t index);

// `"NAME.EXT"`, or `"NAME"` when the extension is empty.
const char *rmn_hdos_file_display_name(const RmnHdosFileList *list, size_t index);

// Size in 256-byte sectors.
uint32_t rmn_hdos_file_size_sectors(const RmnHdosFileList *list, size_t index);

// Size in bytes.
uint64_t rmn_hdos_file_size_bytes(const RmnHdosFileList *list, size_t index);

// Raw HDOS date word.
uint16_t rmn_hdos_file_modified_date_raw(const RmnHdosFileList *list, size_t index);

// Raw HDOS flag byte.
uint8_t rmn_hdos_file_flags_raw(const RmnHdosFileList *list, size_t index);

// HDOS flag letters (subset of "SLWC"), possibly empty.
const char *rmn_hdos_file_flags(const RmnHdosFileList *list, size_t index);

// HDOS catalog date, e.g. "09-May-78", or "No-Date".
const char *rmn_hdos_file_modified_date(const RmnHdosFileList *list, size_t index);

// Opens `path` (UTF-8) as a disk image — raw or qcow2, detected
// by magic — under the P7 claim: read/write with writes denied to others
// (preferred), read-only fallback, fail fast when deny-write cannot be
// obtained. Returns null on failure with a message in `error_out`.
RmnDisk *rmn_disk_open(const char *path, char **error_out);

// Frees a disk handle, releasing the P7 claim. Uncommitted changes are
// discarded (the commit point never reached the file).
void rmn_disk_free(RmnDisk *disk);

// Which P7 mode the open obtained.
RmnAccessMode rmn_disk_mode(const RmnDisk *disk);

// The detected container format.
RmnDiskFormat rmn_disk_format(const RmnDisk *disk);

// The qcow2 version, or 0 for a raw image.
uint32_t rmn_disk_qcow2_version(const RmnDisk *disk);

// The virtual disk size in bytes.
uint64_t rmn_disk_size(const RmnDisk *disk);

// Whether uncommitted changes exist.
bool rmn_disk_is_modified(const RmnDisk *disk);

// Reads the disk's partitions and volumes as they actually are. Free the
// result with `rmn_disk_geometry_free`.
RmnDiskGeometry *rmn_disk_geometry(RmnDisk *disk, char **error_out);

// Frees a geometry snapshot.
void rmn_disk_geometry_free(RmnDiskGeometry *geometry);

// Number of partitions (0 for a partitionless image).
size_t rmn_geometry_partition_count(const RmnDiskGeometry *geometry);

// A partition's 1-based number.
uint32_t rmn_geometry_partition_number(const RmnDiskGeometry *geometry, size_t index);

// A partition's MBR type byte.
uint8_t rmn_geometry_partition_type_byte(const RmnDiskGeometry *geometry, size_t index);

// A partition's pinned type name.
const char *rmn_geometry_partition_type_name(const RmnDiskGeometry *geometry, size_t index);

// A partition's start offset in bytes.
uint64_t rmn_geometry_partition_start_bytes(const RmnDiskGeometry *geometry, size_t index);

// A partition's length in bytes.
uint64_t rmn_geometry_partition_length_bytes(const RmnDiskGeometry *geometry, size_t index);

// Number of volumes actually read (one guest drive letter each).
size_t rmn_geometry_volume_count(const RmnDiskGeometry *geometry);

// The 1-based partition number a volume sits in; returns false for a
// partitionless image.
bool rmn_geometry_volume_partition_number(const RmnDiskGeometry *geometry,
                                          size_t index,
                                          uint32_t *out);

// The volume's FAT kind name ("FAT12" or "FAT16").
const char *rmn_geometry_volume_kind(const RmnDiskGeometry *geometry, size_t index);

// The volume label, or null when it has none.
const char *rmn_geometry_volume_label(const RmnDiskGeometry *geometry, size_t index);

// The volume's offset in bytes.
uint64_t rmn_geometry_volume_offset_bytes(const RmnDiskGeometry *geometry, size_t index);

// The volume's length in bytes.
uint64_t rmn_geometry_volume_length_bytes(const RmnDiskGeometry *geometry, size_t index);

// The volume's cluster size in bytes.
uint64_t rmn_geometry_volume_cluster_bytes(const RmnDiskGeometry *geometry, size_t index);

// The volume's data-cluster count.
uint64_t rmn_geometry_volume_cluster_count(const RmnDiskGeometry *geometry, size_t index);

// The BPB-stated sectors per track; returns false where the boot record
// states none.
bool rmn_geometry_volume_sectors_per_track(const RmnDiskGeometry *geometry,
                                           size_t index,
                                           uint32_t *out);

// The BPB-stated head count; returns false where the boot record states
// none.
bool rmn_geometry_volume_heads(const RmnDiskGeometry *geometry, size_t index, uint32_t *out);

// Lists a directory in volume `volume` ("" = root, "A/B" descends). Free
// with `rmn_fat_entry_list_free`.
RmnFatEntryList *rmn_disk_entries(RmnDisk *disk, size_t volume, const char *path, char **error_out);

// Frees a directory listing.
void rmn_fat_entry_list_free(RmnFatEntryList *list);

// Number of entries in the listing.
size_t rmn_fat_entry_count(const RmnFatEntryList *list);

// An entry's 8.3 name.
const char *rmn_fat_entry_name(const RmnFatEntryList *list, size_t index);

// Whether an entry is a file or a directory.
RmnFatEntryKind rmn_fat_entry_kind(const RmnFatEntryList *list, size_t index);

// An entry's size in bytes (0 for directories).
uint64_t rmn_fat_entry_size_bytes(const RmnFatEntryList *list, size_t index);

// Copies a file's bytes out of volume `volume`. Free with
// `rmn_file_data_free`.
RmnFileData *rmn_disk_read_file(RmnDisk *disk, size_t volume, const char *path, char **error_out);

// The bytes of a read-out file; valid until the handle is freed.
const uint8_t *rmn_file_data_bytes(const RmnFileData *data, size_t *length_out);

// Frees read-out file bytes.
void rmn_file_data_free(RmnFileData *data);

// Writes a file into volume `volume`. Buffered until `rmn_disk_commit`.
bool rmn_disk_write_file(RmnDisk *disk,
                         size_t volume,
                         const char *path,
                         const uint8_t *bytes,
                         size_t length,
                         char **error_out);

// Creates a directory in volume `volume`. Buffered until commit.
bool rmn_disk_make_directory(RmnDisk *disk, size_t volume, const char *path, char **error_out);

// The commit point (P2): everything buffered reaches the image, then a
// flush. Until this call, nothing has touched the file.
bool rmn_disk_commit(RmnDisk *disk, char **error_out);

// Discards everything buffered; the image is untouched.
void rmn_disk_rollback(RmnDisk *disk);

// Which P7 mode the session's open obtained on its source file.
RmnAccessMode rmn_session_access_mode(const RmnSession *session);

// Reads a cataloged HDOS file's contents out of raw image bytes. Free
// with `rmn_file_data_free`.
RmnFileData *rmn_read_hdos_file(const uint8_t *bytes,
                                size_t length,
                                const char *name,
                                char **error_out);

// Reads a cataloged HDOS file out of a session's image bytes. Free with
// `rmn_file_data_free`.
RmnFileData *rmn_session_read_hdos_file(const RmnSession *session,
                                        const char *name,
                                        char **error_out);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* REMANENCE_H */
