/*
 * SPDX-FileCopyrightText: 2026 Paul Galbraith
 * SPDX-License-Identifier: GPL-3.0-only
 */

#ifndef REMANENCE_H
#define REMANENCE_H

/* Generated by cbindgen from crates/remanence-ffi. Do not edit by hand. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

// Stable, machine-readable classification of a library refusal. A fallible
// call writes one beside its error message; the output is untouched on success.
typedef enum {
  REMANENCE_ERROR_CATEGORY_LOCKED = 0,
  REMANENCE_ERROR_CATEGORY_INVALID_IMAGE = 1,
  REMANENCE_ERROR_CATEGORY_UNSUPPORTED = 2,
  REMANENCE_ERROR_CATEGORY_READ_ONLY = 3,
  REMANENCE_ERROR_CATEGORY_NOT_FOUND = 4,
  REMANENCE_ERROR_CATEGORY_NOT_DIRECTORY = 5,
  REMANENCE_ERROR_CATEGORY_IS_DIRECTORY = 6,
  REMANENCE_ERROR_CATEGORY_NO_SPACE = 7,
  REMANENCE_ERROR_CATEGORY_IO = 8,
} RemanenceErrorCategory;

// What role a detected container plays in the image's layering.
typedef enum {
  REMANENCE_CONTAINER_KIND_ARCHIVE,
  REMANENCE_CONTAINER_KIND_IMAGE,
  REMANENCE_CONTAINER_KIND_PHYSICAL_MEDIA,
  REMANENCE_CONTAINER_KIND_FILESYSTEM,
  REMANENCE_CONTAINER_KIND_UNKNOWN,
} RemanenceContainerKind;

// Which layout details a container carries.
typedef enum {
  REMANENCE_LAYOUT_KIND_UNKNOWN,
  REMANENCE_LAYOUT_KIND_ARCHIVE,
  REMANENCE_LAYOUT_KIND_IMAGE,
  REMANENCE_LAYOUT_KIND_PHYSICAL_MEDIA,
  REMANENCE_LAYOUT_KIND_FILESYSTEM,
} RemanenceLayoutKind;

// Sector arrangement across a disk.
typedef enum {
  REMANENCE_SECTOR_LAYOUT_KIND_UNKNOWN,
  REMANENCE_SECTOR_LAYOUT_KIND_FIXED,
  REMANENCE_SECTOR_LAYOUT_KIND_VARIABLE,
} RemanenceSectorLayoutKind;

// The caller's declared intent when opening a disk (P7).
typedef enum {
  REMANENCE_ACCESS_INTENT_READ,
  REMANENCE_ACCESS_INTENT_WRITE,
} RemanenceAccessIntent;

// A disk's access mode — an echo of the declared intent (P7).
typedef enum {
  REMANENCE_ACCESS_MODE_READ_WRITE,
  REMANENCE_ACCESS_MODE_READ_ONLY,
} RemanenceAccessMode;

// The container format a disk image turned out to be.
typedef enum {
  REMANENCE_DISK_FORMAT_RAW,
  REMANENCE_DISK_FORMAT_QCOW2,
  REMANENCE_DISK_FORMAT_VDI,
} RemanenceDiskFormat;

// What a FAT directory entry is.
typedef enum {
  REMANENCE_FAT_ENTRY_KIND_FILE,
  REMANENCE_FAT_ENTRY_KIND_DIRECTORY,
} RemanenceFatEntryKind;

// What to do with a location whose content its neighbour also holds.
typedef enum {
  // Take the profile's declaration, which for a 1541 refuses.
  REMANENCE_DUPLICATE_POLICY_DECLARED = 0,
  REMANENCE_DUPLICATE_POLICY_ADMIT_AS_OBSERVED = 1,
  REMANENCE_DUPLICATE_POLICY_OMIT = 2,
} RemanenceDuplicatePolicy;

// What a projection does with two transitions landing on one cycle.
typedef enum {
  REMANENCE_PROJECTION_POLICY_REFUSE = 0,
  REMANENCE_PROJECTION_POLICY_DECLARE_LOSS = 1,
} RemanenceProjectionPolicy;

// How the selected evidence becomes pulse strength.
typedef enum {
  // Every pulse carries `strength_state`; disagreement across the
  // unselected observations is declared loss rather than expressed.
  REMANENCE_PULSE_STRENGTH_POLICY_DECLARED = 0,
  // A pulse every observation places within `strength_window_cycles`
  // is strong; one only some corroborate is weak.
  REMANENCE_PULSE_STRENGTH_POLICY_FROM_AGREEMENT = 1,
} RemanencePulseStrengthPolicy;

// Where the medium's circle begins.
typedef enum {
  // The track's own seam, which is what the profile declares.
  REMANENCE_ORIGIN_POLICY_DECLARED = 0,
  // The angle in `origin_cycles`, stated outright by the caller.
  REMANENCE_ORIGIN_POLICY_ANGLE = 1,
} RemanenceOriginPolicy;

// What the device's leading structure turned out to be. The report states
// this rather than leaving a caller to reconstruct it from empty lists.
typedef enum {
  // All zero: a blank disk, which is an answer.
  REMANENCE_DISK_CONTENT_BLANK,
  // A partition schema was recognized, whether or not a volume composed.
  REMANENCE_DISK_CONTENT_SCHEMA,
  // No schema, and the whole device is one volume.
  REMANENCE_DISK_CONTENT_DIRECT_VOLUME,
  // Not blank, and no adapter claims it. An outcome, not a refusal.
  REMANENCE_DISK_CONTENT_UNKNOWN_NONBLANK,
} RemanenceDiskContent;

// How a schema declares a region: data, which composition may consume, or
// structure, which it may not.
typedef enum {
  REMANENCE_REGION_ROLE_DATA,
  REMANENCE_REGION_ROLE_CONTAINER,
} RemanenceRegionRole;

// Where a volume's storage came from.
typedef enum {
  REMANENCE_VOLUME_ORIGIN_WHOLE_DEVICE,
  REMANENCE_VOLUME_ORIGIN_REGIONS,
} RemanenceVolumeOrigin;

// What one letter turned out to name.
typedef enum {
  // A volume on an asserted device, named by its report's identity.
  REMANENCE_LETTER_OUTCOME_VOLUME = 0,
  // A device the caller declared a resident driver placed here. The
  // library composes no volume for it and invents no identity.
  REMANENCE_LETTER_OUTCOME_DECLARED_DEVICE = 1,
  // DOS's phantom second floppy: the same drive as the letter before
  // it, not a second volume.
  REMANENCE_LETTER_OUTCOME_PHANTOM = 2,
  // The claimed rules could not settle this letter.
  REMANENCE_LETTER_OUTCOME_UNDETERMINED = 3,
} RemanenceLetterOutcome;

// An open archive listing, holding the claim on its file.
typedef struct RemanenceArchive RemanenceArchive;

// An open capture set, holding the claim on its archive.
typedef struct RemanenceCaptureSet RemanenceCaptureSet;

// A borrowed view of the medium in one storage device.
//
// **The session owns this; never free it.** It stays valid until the
// device is detached or the session is freed.
//
// It names the medium by session and attachment identity rather than by
// pointer, and re-resolves on every call. That is deliberate: a later
// attach may reallocate the session's device storage, so a cached
// pointer to the medium itself would dangle silently.
typedef struct RemanenceDisk RemanenceDisk;

// A snapshot of one disk's layered inspection. Owned by the caller and
// released with `remanence_disk_report_free`; every string and record
// reached through it is borrowed from it and dies with it.
typedef struct RemanenceDiskReport RemanenceDiskReport;

// The machine facts a caller asserts, in the order they were asserted.
typedef struct RemanenceDosMachine RemanenceDosMachine;

// A composed drive-letter mapping. Owned by the caller and released with
// `remanence_drive_map_free`; every string reached through it is borrowed
// from it and dies with it.
typedef struct RemanenceDriveMap RemanenceDriveMap;

// A directory listing.
typedef struct RemanenceFatEntryList RemanenceFatEntryList;

// Bytes read out of a volume or catalog.
typedef struct RemanenceFileData RemanenceFileData;

// A parsed HDOS directory listing.
typedef struct RemanenceHdosFileList RemanenceHdosFileList;

// The result of identifying a disk's image.
typedef struct RemanenceIdentification RemanenceIdentification;

// A mastered medium, held in the session.
typedef struct RemanenceMasteredMedium RemanenceMasteredMedium;

// A planned reduction: everything computed, nothing written.
typedef struct RemanenceMasteringPlan RemanenceMasteringPlan;

// An opened P64 image, holding its claim on the file and the medium it
// decoded into private session storage.
typedef struct RemanenceP64Image RemanenceP64Image;

// What a container carried, or will carry, of one mastered medium.
typedef struct RemanenceP64Report RemanenceP64Report;

// A recognition result, ranked highest confidence first.
typedef struct RemanenceRecognition RemanenceRecognition;

// An open session: the machine scope, holding a set of family-typed
// storage devices (P32).
typedef struct RemanenceSession RemanenceSession;

// One zone as a profile declares it, and what the capture recovered of
// it.
typedef struct {
  uint64_t first_location;
  uint64_t last_location;
  // What the family claims one location in this zone holds.
  uint32_t records_declared;
  uint64_t locations_declared;
  uint64_t locations_claimed;
  // The cell this zone claims, in thousandths of a reference cycle.
  uint64_t nominal_cell_millicycles;
} RemanenceZoneClaim;

// What the probe found at one source position. Every `has_*` flag says
// whether the value beside it was established at all: an absence is a
// finding, not a zero.
typedef struct {
  uint64_t position_numerator;
  uint64_t position_denominator;
  bool has_head;
  uint64_t head;
  // The family location this position addresses, where the family's
  // addressing covers it at all.
  bool has_family_location;
  uint64_t family_location;
  bool has_zone;
  uint32_t zone;
  uint32_t records;
  // The bit distance between record starts, where it repeats.
  bool has_record_bits;
  uint64_t record_bits;
  // How far that spacing departs from its own median. Zero is a
  // spacing that repeats to the bit.
  uint64_t record_bits_deviation;
  // The one departure from it, as an angle in reference-clock cycles.
  bool has_seam;
  uint64_t seam_cycles;
  // The derived cell projected onto the family's nominal rotation,
  // in thousandths of a reference cycle, beside what the zone claims.
  bool has_cell;
  uint64_t cell_millicycles;
  bool has_nominal_cell;
  uint64_t nominal_cell_millicycles;
  // How much of the interval population classified, per thousand.
  uint32_t resolved_permille;
  uint32_t observations;
  uint32_t observations_agreeing;
  // The adjacent position holding the same content, where one does.
  bool has_duplicate;
  uint64_t duplicate_numerator;
  uint64_t duplicate_denominator;
  bool claimed;
} RemanenceLocationVerdict;

// The complete declared policy for one reduction. There is no default:
// every field is a decision about evidence, and a reduction no input
// names is a refusal.
typedef struct {
  // The captured head supplying the family's one recorded surface.
  uint64_t side;
  // Which observation of each location is used.
  uint64_t observation_ordinal;
  RemanenceDuplicatePolicy duplicate;
  RemanenceProjectionPolicy projection;
  RemanencePulseStrengthPolicy pulse_strength;
  uint32_t strength_state;
  uint64_t strength_window_cycles;
  RemanenceOriginPolicy origin;
  uint64_t origin_cycles;
  // What makes any stochastic element reproducible.
  uint64_t seed;
} RemanenceMasteringPolicy;

// One half-track the medium will hold.
typedef struct {
  uint64_t source_position_numerator;
  uint64_t source_position_denominator;
  uint64_t half_track_numerator;
  uint64_t half_track_denominator;
  uint64_t observation_ordinal;
  uint64_t pulses;
  uint64_t strong_pulses;
  uint64_t weak_pulses;
  uint64_t origin_cycles;
  bool has_seam;
  uint64_t seam_cycles;
} RemanenceMasteredLocation;

// One half-track a P64 holds, in the container's addressing and the
// family's both.
typedef struct {
  // The container's own index byte, side bit included.
  uint8_t index;
  uint64_t side;
  uint64_t half_track_numerator;
  uint64_t half_track_denominator;
  uint64_t pulses;
  // Pulses that always trigger, that sometimes do, and that never do.
  uint64_t strong_pulses;
  uint64_t weak_pulses;
  uint64_t absent_pulses;
} RemanenceP64HalfTrack;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

// Returns the library version as a static string. Do not free.
const char *remanence_version(void);

// The stated default session cache bound, in bytes: what an open
// without a declared bound uses.
uint64_t remanence_default_cache_bytes(void);

// Frees a string returned through an `error_out` or `error_rule_out`
// parameter.
//
// A fallible call writes three things on failure: the stable
// category, which says how to behave; the human diagnostic; and,
// where the refusal is one of an enumerated set of rules a format,
// namespace, or grammar defines, the stable identity of the rule the input
// broke. `error_rule_out` is null where no such rule set applies, which is
// the ordinary case rather than an omission — the rule identity never
// substitutes for the category. Each output is optional; passing null for
// any of them declines it. The DOS 8.3 namespace owns the set the file
// verbs draw on: `empty-base`, `base-too-long`, `extension-too-long`,
// `separator`, `excluded-character`, `reserved-device-name`,
// `surrounding-space`.
void remanence_string_free(char *string);

// The artifact the disk was opened from (the archive path for archive inputs).
const char *remanence_disk_path(const RemanenceDisk *disk);

// The resolved image path (the entry name for archive inputs).
const char *remanence_disk_image_path(const RemanenceDisk *disk);

// The resolved image's size in bytes.
uint64_t remanence_disk_image_size_bytes(const RemanenceDisk *disk);

// Reads `length` bytes of the resolved image at `offset` into
// `buffer_out` — the bounded access form: the image streams from its
// backing and is never resident whole. Returns false on failure and
// stores a message in `error_out` (free with `remanence_string_free`).
bool remanence_disk_read_at(const RemanenceDisk *disk,
                            uint64_t offset,
                            uint8_t *buffer_out,
                            size_t length,
                            RemanenceErrorCategory *error_category_out,
                            char **error_out,
                            char **error_rule_out);

// Identifies the image's container layers and probable filesystem. Free the
// result with `remanence_identification_free`.
RemanenceIdentification *remanence_disk_identify(const RemanenceDisk *disk);

// Frees an identification handle.
void remanence_identification_free(RemanenceIdentification *identification);

// Whether the disk reported unsaved modifications at identify time.
bool remanence_identification_modified(const RemanenceIdentification *identification);

// Number of detected container layers.
size_t remanence_identification_container_count(const RemanenceIdentification *identification);

// Number of evidence lines.
size_t remanence_identification_evidence_count(const RemanenceIdentification *identification);

// One evidence line, or null when out of range.
const char *remanence_identification_evidence(const RemanenceIdentification *identification,
                                              size_t index);

// The container's kind, or `RemanenceContainerKind::Unknown` when out of range.
RemanenceContainerKind remanence_container_kind(const RemanenceIdentification *identification,
                                                size_t index);

// The container's id (e.g. "h8d", "zip", "hdos").
const char *remanence_container_id(const RemanenceIdentification *identification, size_t index);

// The container's human-readable name.
const char *remanence_container_name(const RemanenceIdentification *identification, size_t index);

// Detection confidence, 0-100.
uint8_t remanence_container_confidence(const RemanenceIdentification *identification, size_t index);

// Whether the container matched a known format.
bool remanence_container_known(const RemanenceIdentification *identification, size_t index);

// Current size in bytes; returns false when unknown.
bool remanence_container_current_bytes(const RemanenceIdentification *identification,
                                       size_t index,
                                       uint64_t *out);

// Expected size in bytes; returns false when unknown.
bool remanence_container_expected_bytes(const RemanenceIdentification *identification,
                                        size_t index,
                                        uint64_t *out);

// Which layout details this container carries.
RemanenceLayoutKind remanence_container_layout_kind(const RemanenceIdentification *identification,
                                                    size_t index);

// Archive layout: the archive file path; null for other layouts.
const char *remanence_container_archive_path(const RemanenceIdentification *identification,
                                             size_t index);

// Archive layout: the entry name inside the archive; null for other layouts.
const char *remanence_container_archive_entry_name(const RemanenceIdentification *identification,
                                                   size_t index);

// Archive layout: compressed entry size; returns false when unknown.
bool remanence_container_archive_compressed_size(const RemanenceIdentification *identification,
                                                 size_t index,
                                                 uint64_t *out);

// Archive layout: uncompressed entry size; returns false when unknown.
bool remanence_container_archive_uncompressed_size(const RemanenceIdentification *identification,
                                                   size_t index,
                                                   uint64_t *out);

// Image layout: payload offset in bytes; returns false when unknown.
bool remanence_container_image_payload_offset(const RemanenceIdentification *identification,
                                              size_t index,
                                              uint64_t *out);

// Image layout: payload length in bytes; returns false when unknown.
bool remanence_container_image_payload_length(const RemanenceIdentification *identification,
                                              size_t index,
                                              uint64_t *out);

// Physical media layout: whether disk geometry is known.
bool remanence_container_has_disk_layout(const RemanenceIdentification *identification,
                                         size_t index);

// Disk layout: media kind (e.g. "floppy"); null when unknown.
const char *remanence_container_disk_media_kind(const RemanenceIdentification *identification,
                                                size_t index);

// Disk layout: sector size in bytes; returns false when unknown.
bool remanence_container_disk_sector_size(const RemanenceIdentification *identification,
                                          size_t index,
                                          uint64_t *out);

// Disk layout: cylinder count; returns false when unknown.
bool remanence_container_disk_cylinders(const RemanenceIdentification *identification,
                                        size_t index,
                                        uint32_t *out);

// Disk layout: side count; returns false when unknown.
bool remanence_container_disk_sides(const RemanenceIdentification *identification,
                                    size_t index,
                                    uint32_t *out);

// Disk layout: how sectors are arranged.
RemanenceSectorLayoutKind remanence_container_disk_sector_layout_kind(const RemanenceIdentification *identification,
                                                                      size_t index);

// Disk layout: sectors per track for fixed layouts; 0 otherwise.
uint32_t remanence_container_disk_sectors_per_track(const RemanenceIdentification *identification,
                                                    size_t index);

// Disk layout: per-track entry count for variable layouts; 0 otherwise.
size_t remanence_container_disk_track_count(const RemanenceIdentification *identification,
                                            size_t index);

// Disk layout: one per-track entry for variable layouts. Returns false when
// out of range. `has_sector_size` and `sector_size` report the optional
// per-track sector size.
bool remanence_container_disk_track(const RemanenceIdentification *identification,
                                    size_t index,
                                    size_t track_index,
                                    uint32_t *cylinder,
                                    uint32_t *side,
                                    uint32_t *sectors,
                                    bool *has_sector_size,
                                    uint64_t *sector_size);

// Disk layout: total sector count; returns false when unknown.
bool remanence_container_disk_total_sectors(const RemanenceIdentification *identification,
                                            size_t index,
                                            uint64_t *out);

// Filesystem layout: offset in bytes; returns false when unknown.
bool remanence_container_fs_offset_bytes(const RemanenceIdentification *identification,
                                         size_t index,
                                         uint64_t *out);

// Filesystem layout: length in bytes; returns false when unknown.
bool remanence_container_fs_length_bytes(const RemanenceIdentification *identification,
                                         size_t index,
                                         uint64_t *out);

// Parses the HDOS directory from raw image bytes. Returns null on failure and
// stores a message in `error_out` (free with `remanence_string_free`).
RemanenceHdosFileList *remanence_list_hdos_files(const uint8_t *bytes,
                                                 size_t length,
                                                 RemanenceErrorCategory *error_category_out,
                                                 char **error_out,
                                                 char **error_rule_out);

// Parses the HDOS directory from the disk's image. Returns null on
// failure and stores a message in `error_out` (free with `remanence_string_free`).
RemanenceHdosFileList *remanence_disk_list_hdos_files(const RemanenceDisk *disk,
                                                      RemanenceErrorCategory *error_category_out,
                                                      char **error_out,
                                                      char **error_rule_out);

// Frees an HDOS file list handle.
void remanence_hdos_file_list_free(RemanenceHdosFileList *list);

// Number of files in the listing.
size_t remanence_hdos_file_count(const RemanenceHdosFileList *list);

// File name without extension, e.g. "HDOS".
const char *remanence_hdos_file_name(const RemanenceHdosFileList *list, size_t index);

// File extension, possibly empty, e.g. "SYS".
const char *remanence_hdos_file_extension(const RemanenceHdosFileList *list, size_t index);

// `"NAME.EXT"`, or `"NAME"` when the extension is empty.
const char *remanence_hdos_file_display_name(const RemanenceHdosFileList *list, size_t index);

// Size in 256-byte sectors.
uint32_t remanence_hdos_file_size_sectors(const RemanenceHdosFileList *list, size_t index);

// Size in bytes.
uint64_t remanence_hdos_file_size_bytes(const RemanenceHdosFileList *list, size_t index);

// Raw HDOS date word.
uint16_t remanence_hdos_file_modified_date_raw(const RemanenceHdosFileList *list, size_t index);

// Raw HDOS flag byte.
uint8_t remanence_hdos_file_flags_raw(const RemanenceHdosFileList *list, size_t index);

// HDOS flag letters (subset of "SLWC"), possibly empty.
const char *remanence_hdos_file_flags(const RemanenceHdosFileList *list, size_t index);

// HDOS catalog date, e.g. "09-May-78", or "No-Date".
const char *remanence_hdos_file_modified_date(const RemanenceHdosFileList *list, size_t index);

// Opens an empty session — the machine scope. Devices are attached and
// detached over its life; the set is not fixed at open. Free with
// `remanence_session_free`.
RemanenceSession *remanence_session_new(void);

// Frees a session, detaching every device and releasing every P7 claim.
// Every borrowed medium view obtained from it becomes invalid.
void remanence_session_free(RemanenceSession *session);

// Attaches the medium at `path` (UTF-8) — a raw disk image, or
// `archive[/entry]` — to a new device in the lowest free slot of its
// family, writing the attachment identity it took (such as `hdd0`) to
// `attachment_out`. Free that string with `remanence_string_free`. A
// `Write` intent claims the medium exclusively and fails at the open
// when the claim cannot be secured, never by falling back. Returns
// false on failure.
bool remanence_session_attach(RemanenceSession *session,
                              const char *path,
                              RemanenceAccessIntent intent,
                              char **attachment_out,
                              RemanenceErrorCategory *error_category_out,
                              char **error_out,
                              char **error_rule_out);

// Attaches the medium at `path` to the slot `attachment` names (such as
// `hdd1`). The caller chooses the slot, never the name. A slot already
// occupied is refused rather than displaced, and a family this release
// does not claim is refused by name (P3).
bool remanence_session_attach_at(RemanenceSession *session,
                                 const char *attachment,
                                 const char *path,
                                 RemanenceAccessIntent intent,
                                 RemanenceErrorCategory *error_category_out,
                                 char **error_out,
                                 char **error_rule_out);

// Detaches the device at `attachment`, releasing its medium's P7 claim
// and freeing the slot. Borrowed medium views for that device become
// invalid.
bool remanence_session_detach(RemanenceSession *session,
                              const char *attachment,
                              RemanenceErrorCategory *error_category_out,
                              char **error_out,
                              char **error_rule_out);

// How many devices the session holds.
size_t remanence_session_device_count(const RemanenceSession *session);

// Writes the attachment identity of device `index` to
// `attachment_out`, freed with `remanence_string_free`. Returns false
// when `index` is out of range.
bool remanence_session_device_attachment(const RemanenceSession *session,
                                         size_t index,
                                         char **attachment_out);

// A **borrowed** view of the medium in the device at `attachment`.
//
// The session owns it; never free it. It stays valid until that device
// is detached or the session is freed. Returns null when nothing is
// attached there.
RemanenceDisk *remanence_session_medium(RemanenceSession *session, const char *attachment);

// The disk session's access mode — an echo of the declared intent.
RemanenceAccessMode remanence_disk_mode(const RemanenceDisk *disk);

// The detected container format.
RemanenceDiskFormat remanence_disk_format(const RemanenceDisk *disk);

// The qcow2 version, or 0 for an image of any other format.
uint32_t remanence_disk_qcow2_version(const RemanenceDisk *disk);

// The VDI version's major part, or 0 for an image of any other format.
uint32_t remanence_disk_vdi_version_major(const RemanenceDisk *disk);

// The VDI version's minor part, or 0 for an image of any other format.
// Read it beside the major part: on its own, 0 is both "minor zero" and
// "not a VDI".
uint32_t remanence_disk_vdi_version_minor(const RemanenceDisk *disk);

// The virtual disk size in bytes.
uint64_t remanence_disk_size(const RemanenceDisk *disk);

// Whether uncommitted changes exist.
bool remanence_disk_is_modified(const RemanenceDisk *disk);

// Lists a directory in `volume_id` ("" = root, "A/B" descends). Free
// with `remanence_fat_entry_list_free`.
RemanenceFatEntryList *remanence_disk_entries(RemanenceDisk *disk,
                                              uint64_t volume_id,
                                              const char *path,
                                              RemanenceErrorCategory *error_category_out,
                                              char **error_out,
                                              char **error_rule_out);

// Answers one path in `volume_id` (U3): a one-entry listing when
// something exists there, an empty listing when nothing does — a
// missing leaf, a missing parent, or a parent that is a file alike.
// Absence is an answer, distinguished from failure, which returns null
// with the error set. Free with `remanence_fat_entry_list_free`.
RemanenceFatEntryList *remanence_disk_stat(RemanenceDisk *disk,
                                           uint64_t volume_id,
                                           const char *path,
                                           RemanenceErrorCategory *error_category_out,
                                           char **error_out,
                                           char **error_rule_out);

// Frees a directory listing.
void remanence_fat_entry_list_free(RemanenceFatEntryList *list);

// Number of entries in the listing.
size_t remanence_fat_entry_count(const RemanenceFatEntryList *list);

// An entry's 8.3 name.
const char *remanence_fat_entry_name(const RemanenceFatEntryList *list, size_t index);

// Whether an entry is a file or a directory.
RemanenceFatEntryKind remanence_fat_entry_kind(const RemanenceFatEntryList *list, size_t index);

// An entry's size in bytes (0 for directories).
uint64_t remanence_fat_entry_size_bytes(const RemanenceFatEntryList *list, size_t index);

// Copies a file's bytes out of `volume_id`. Free with
// `remanence_file_data_free`.
RemanenceFileData *remanence_disk_read_file(RemanenceDisk *disk,
                                            uint64_t volume_id,
                                            const char *path,
                                            RemanenceErrorCategory *error_category_out,
                                            char **error_out,
                                            char **error_rule_out);

// Reads part of a file into `buffer_out` — the streamed form beside
// `remanence_disk_read_file`: exactly `length` bytes at `offset`,
// which must lie within the file.
bool remanence_disk_read_file_at(RemanenceDisk *disk,
                                 uint64_t volume_id,
                                 const char *path,
                                 uint64_t offset,
                                 uint8_t *buffer_out,
                                 size_t length,
                                 RemanenceErrorCategory *error_category_out,
                                 char **error_out,
                                 char **error_rule_out);

// Sets a file's size, creating it when absent — with
// `remanence_disk_write_file_at`, the streamed replacement for
// `remanence_disk_write_file`. Buffered until commit.
bool remanence_disk_resize_file(RemanenceDisk *disk,
                                uint64_t volume_id,
                                const char *path,
                                uint64_t size,
                                RemanenceErrorCategory *error_category_out,
                                char **error_out,
                                char **error_rule_out);

// Writes part of a file in place — the streamed form beside
// `remanence_disk_write_file`: the span must lie within the file's
// current size. Buffered until commit.
bool remanence_disk_write_file_at(RemanenceDisk *disk,
                                  uint64_t volume_id,
                                  const char *path,
                                  uint64_t offset,
                                  const uint8_t *bytes,
                                  size_t length,
                                  RemanenceErrorCategory *error_category_out,
                                  char **error_out,
                                  char **error_rule_out);

// The bytes of a read-out file; valid until the handle is freed.
const uint8_t *remanence_file_data_bytes(const RemanenceFileData *data, size_t *length_out);

// Frees read-out file bytes.
void remanence_file_data_free(RemanenceFileData *data);

// Writes a file into `volume_id`. An existing file is overwritten —
// shorter or longer, its old clusters released and reclaimed — while
// an existing directory is refused. Buffered until `remanence_disk_commit`.
bool remanence_disk_write_file(RemanenceDisk *disk,
                               uint64_t volume_id,
                               const char *path,
                               const uint8_t *bytes,
                               size_t length,
                               RemanenceErrorCategory *error_category_out,
                               char **error_out,
                               char **error_rule_out);

// Ensures a directory exists in `volume_id`: missing parents are
// created, and a path that already leads to a directory succeeds
// unchanged. Buffered until commit.
bool remanence_disk_make_directory(RemanenceDisk *disk,
                                   uint64_t volume_id,
                                   const char *path,
                                   RemanenceErrorCategory *error_category_out,
                                   char **error_out,
                                   char **error_rule_out);

// The commit point (P2): everything buffered reaches the image, then a
// flush. Until this call, nothing has touched the file. The commit is
// durable (P9): a private recovery journal is armed before the first
// byte of the file changes, so an interruption at any point leaves
// state the next open reconciles to wholly the old image or wholly
// the committed new one.
bool remanence_disk_commit(RemanenceDisk *disk,
                           RemanenceErrorCategory *error_category_out,
                           char **error_out,
                           char **error_rule_out);

// Discards everything buffered; the image is untouched.
void remanence_disk_rollback(RemanenceDisk *disk);

// Reads a cataloged HDOS file's contents out of raw image bytes. Free
// with `remanence_file_data_free`.
RemanenceFileData *remanence_read_hdos_file(const uint8_t *bytes,
                                            size_t length,
                                            const char *name,
                                            RemanenceErrorCategory *error_category_out,
                                            char **error_out,
                                            char **error_rule_out);

// Reads a cataloged HDOS file out of the disk's image. Free with
// `remanence_file_data_free`.
RemanenceFileData *remanence_disk_read_hdos_file(const RemanenceDisk *disk,
                                                 const char *name,
                                                 RemanenceErrorCategory *error_category_out,
                                                 char **error_out,
                                                 char **error_rule_out);

// Opens the archive at `path` (UTF-8) and reads its entry list. A path
// naming no archive format this library reads is refused by name.
// Returns null on failure and stores a message in `error_out` (free with
// `remanence_string_free`).
RemanenceArchive *remanence_archive_open(const char *path,
                                         RemanenceErrorCategory *error_category_out,
                                         char **error_out,
                                         char **error_rule_out);

// Frees an archive handle, releasing its claim on the file.
void remanence_archive_free(RemanenceArchive *archive);

// The path the archive was opened from.
const char *remanence_archive_path(const RemanenceArchive *archive);

// The archive format's stable identifier, e.g. "zip" or "7z".
const char *remanence_archive_format_id(const RemanenceArchive *archive);

// The archive format's human-readable name.
const char *remanence_archive_format_name(const RemanenceArchive *archive);

// Which P7 mode the open obtained on the archive file.
RemanenceAccessMode remanence_archive_access_mode(const RemanenceArchive *archive);

// The archive file's own size in bytes.
uint64_t remanence_archive_size_bytes(const RemanenceArchive *archive);

// Number of entries the archive holds.
size_t remanence_archive_entry_count(const RemanenceArchive *archive);

// One entry's `/`-separated path inside the archive, or null when out
// of range.
const char *remanence_archive_entry_name(const RemanenceArchive *archive, size_t index);

// Whether the entry is a directory.
bool remanence_archive_entry_is_dir(const RemanenceArchive *archive, size_t index);

// The entry's size once decoded, as the archive declares it; 0 when out
// of range.
uint64_t remanence_archive_entry_uncompressed_size(const RemanenceArchive *archive, size_t index);

// The entry's packed size; returns false when the grammar attributes
// none to a single entry — a member of a solid 7z folder — or when the
// index is out of range.
bool remanence_archive_entry_compressed_size(const RemanenceArchive *archive,
                                             size_t index,
                                             uint64_t *out);

// Opens the KryoFlux capture set held by `path` (UTF-8) — an archive
// this library reads, optionally followed by the subtree inside it that
// holds the members — with the stated default session cache bound.
// An incomplete, duplicate, contradictory, or unrelated member refuses
// the whole set. Returns null on failure and stores a message in
// `error_out` (free with `remanence_string_free`).
RemanenceCaptureSet *remanence_capture_set_open(const char *path,
                                                RemanenceErrorCategory *error_category_out,
                                                char **error_out,
                                                char **error_rule_out);

// Opens a capture set as `remanence_capture_set_open` does, under a
// declared cache bound: at most `cache_bytes` of the decoded capture
// stays resident. The bound narrows the working set; it never refuses
// service.
RemanenceCaptureSet *remanence_capture_set_open_with_cache(const char *path,
                                                           uint64_t cache_bytes,
                                                           RemanenceErrorCategory *error_category_out,
                                                           char **error_out,
                                                           char **error_rule_out);

// Frees a capture-set handle, releasing its claim on the archive and
// discarding the private session storage the capture decoded into.
void remanence_capture_set_free(RemanenceCaptureSet *set);

// The path the set was opened from.
const char *remanence_capture_set_path(const RemanenceCaptureSet *set);

// The subtree inside the archive the members were read from, or null
// when the whole archive is the set.
const char *remanence_capture_set_subtree(const RemanenceCaptureSet *set);

// The capture format's stable identifier, "kryoflux".
const char *remanence_capture_set_format_id(const RemanenceCaptureSet *set);

// The capture format's human-readable name.
const char *remanence_capture_set_format_name(const RemanenceCaptureSet *set);

// The archive grammar the members were read through, e.g. "7z".
const char *remanence_capture_set_archive_format_id(const RemanenceCaptureSet *set);

// Which P7 mode the open obtained on the archive file.
RemanenceAccessMode remanence_capture_set_access_mode(const RemanenceCaptureSet *set);

// The capture's declared timing basis, as an exact ratio of ticks per
// second. Returns false when the handle is null.
bool remanence_capture_set_ticks_per_second(const RemanenceCaptureSet *set,
                                            uint64_t *numerator_out,
                                            uint64_t *denominator_out);

// How many bytes of private session storage the decoded capture
// occupies.
uint64_t remanence_capture_set_backing_bytes(const RemanenceCaptureSet *set);

// How much of that backing is currently resident. The capture is never
// held whole.
uint64_t remanence_capture_set_resident_bytes(const RemanenceCaptureSet *set);

// Number of evidence lines behind the recognition.
size_t remanence_capture_set_evidence_count(const RemanenceCaptureSet *set);

// One evidence line, or null when out of range.
const char *remanence_capture_set_evidence(const RemanenceCaptureSet *set, size_t index);

// Number of members the set holds.
size_t remanence_capture_set_member_count(const RemanenceCaptureSet *set);

// One member's catalog identity, or null when out of range.
const char *remanence_capture_set_member_entry_name(const RemanenceCaptureSet *set, size_t member);

// One member's size in bytes as the catalog declares it; 0 when out of
// range.
uint64_t remanence_capture_set_member_entry_bytes(const RemanenceCaptureSet *set, size_t member);

// One member's drive-step position, as an exact ratio. Returns false
// when out of range.
bool remanence_capture_set_member_position(const RemanenceCaptureSet *set,
                                           size_t member,
                                           uint64_t *numerator_out,
                                           uint64_t *denominator_out);

// The head that captured this position; returns false when the source
// numbers no head, which is a different fact from head zero, or when
// the index is out of range.
bool remanence_capture_set_member_head(const RemanenceCaptureSet *set,
                                       size_t member,
                                       uint64_t *out);

// Number of things recorded as qualified about this member.
size_t remanence_capture_set_member_issue_count(const RemanenceCaptureSet *set, size_t member);

// One issue's stable code, or null when out of range.
const char *remanence_capture_set_member_issue_code(const RemanenceCaptureSet *set,
                                                    size_t member,
                                                    size_t issue);

// One issue's human-readable detail, or null when out of range.
const char *remanence_capture_set_member_issue_detail(const RemanenceCaptureSet *set,
                                                      size_t member,
                                                      size_t issue);

// Number of source transfers recorded at this member's location.
size_t remanence_capture_set_member_run_count(const RemanenceCaptureSet *set, size_t member);

// One run's place in the member's recorded order; 0 when out of range.
uint64_t remanence_capture_set_run_ordinal(const RemanenceCaptureSet *set,
                                           size_t member,
                                           size_t run);

// How many flux transitions the run recorded.
uint64_t remanence_capture_set_run_transitions(const RemanenceCaptureSet *set,
                                               size_t member,
                                               size_t run);

// The last transition's tick: the extent of what was recorded, not a
// circumference. A run states no period.
uint64_t remanence_capture_set_run_extent_ticks(const RemanenceCaptureSet *set,
                                                size_t member,
                                                size_t run);

// How many timed markers sit on channels parallel to the run's flux.
uint64_t remanence_capture_set_run_markers(const RemanenceCaptureSet *set,
                                           size_t member,
                                           size_t run);

// How many of those markers are index events.
uint64_t remanence_capture_set_run_index_markers(const RemanenceCaptureSet *set,
                                                 size_t member,
                                                 size_t run);

// The result the capture tool declared for this transfer, where it
// declared one; zero is a clean read. Returns false when it declared
// none or the index is out of range.
bool remanence_capture_set_run_transfer_result(const RemanenceCaptureSet *set,
                                               size_t member,
                                               size_t run,
                                               uint32_t *out);

// Transitions recorded before the run's first index: evidence that
// bounding into circular observations does not consume.
uint64_t remanence_capture_set_run_transitions_before_first_index(const RemanenceCaptureSet *set,
                                                                  size_t member,
                                                                  size_t run);

// Transitions recorded after the run's last index, on the same terms.
uint64_t remanence_capture_set_run_transitions_after_last_index(const RemanenceCaptureSet *set,
                                                                size_t member,
                                                                size_t run);

// How many circular observations the run's indices bounded.
size_t remanence_capture_set_run_observation_count(const RemanenceCaptureSet *set,
                                                   size_t member,
                                                   size_t run);

// One observation's place in the location's source-record order. Not a
// rank: nothing here says it is a good or complete revolution.
uint64_t remanence_capture_set_observation_ordinal(const RemanenceCaptureSet *set,
                                                   size_t member,
                                                   size_t run,
                                                   size_t observation);

// The observation's declared circumference, in the capture's own ticks.
uint64_t remanence_capture_set_observation_span_ticks(const RemanenceCaptureSet *set,
                                                      size_t member,
                                                      size_t run,
                                                      size_t observation);

// How many transitions the observation holds.
uint64_t remanence_capture_set_observation_transitions(const RemanenceCaptureSet *set,
                                                       size_t member,
                                                       size_t run,
                                                       size_t observation);

// How many markers the observation holds.
uint64_t remanence_capture_set_observation_markers(const RemanenceCaptureSet *set,
                                                   size_t member,
                                                   size_t run,
                                                   size_t observation);

// Recognizes the drive family a capture set was recorded under. Every
// enrolled profile is consulted and what claims the capture is ranked;
// a capture no profile claims is a named refusal. Returns null on
// failure and stores a message in `error_out` (free with
// `remanence_string_free`).
RemanenceRecognition *remanence_capture_set_recognize(const RemanenceCaptureSet *set,
                                                      RemanenceErrorCategory *error_category_out,
                                                      char **error_out,
                                                      char **error_rule_out);

// Recognizes the capture against one named profile, whether or not it
// would have won the ranking. A profile this build does not enroll is
// refused by name.
RemanenceRecognition *remanence_capture_set_recognize_as(const RemanenceCaptureSet *set,
                                                         const char *profile_id,
                                                         RemanenceErrorCategory *error_category_out,
                                                         char **error_out,
                                                         char **error_rule_out);

// Frees a recognition handle.
void remanence_recognition_free(RemanenceRecognition *recognition);

// The profile the caller pinned, or null when the ranking was open.
const char *remanence_recognition_pinned(const RemanenceRecognition *recognition);

// Number of evidence lines about the recognition itself.
size_t remanence_recognition_evidence_count(const RemanenceRecognition *recognition);

// One of those lines, or null when out of range.
const char *remanence_recognition_evidence(const RemanenceRecognition *recognition, size_t index);

// How many profiles claimed the capture, highest confidence first.
size_t remanence_recognition_verdict_count(const RemanenceRecognition *recognition);

// One verdict's profile identifier, or null when out of range.
const char *remanence_recognition_profile_id(const RemanenceRecognition *recognition,
                                             size_t verdict);

// One verdict's human-readable family name.
const char *remanence_recognition_profile_name(const RemanenceRecognition *recognition,
                                               size_t verdict);

// Detection confidence, 0-100. Never an answer on its own: read the
// evidence beside it.
uint8_t remanence_recognition_confidence(const RemanenceRecognition *recognition, size_t verdict);

// How many of the profile's declared locations the capture claimed,
// and how many it declares.
uint32_t remanence_recognition_locations_claimed(const RemanenceRecognition *recognition,
                                                 size_t verdict);

uint64_t remanence_recognition_locations_declared(const RemanenceRecognition *recognition,
                                                  size_t verdict);

// Number of evidence lines behind this verdict.
size_t remanence_recognition_verdict_evidence_count(const RemanenceRecognition *recognition,
                                                    size_t verdict);

// One of those lines, or null when out of range.
const char *remanence_recognition_verdict_evidence(const RemanenceRecognition *recognition,
                                                   size_t verdict,
                                                   size_t index);

// How many density zones the profile declares.
size_t remanence_recognition_zone_count(const RemanenceRecognition *recognition, size_t verdict);

// One zone, written into `out`. Returns false when out of range.
bool remanence_recognition_zone(const RemanenceRecognition *recognition,
                                size_t verdict,
                                size_t zone,
                                RemanenceZoneClaim *out);

// How many source positions the probe accounted for.
size_t remanence_recognition_location_count(const RemanenceRecognition *recognition,
                                            size_t verdict);

// One position's findings, written into `out`. Returns false when out
// of range.
bool remanence_recognition_location(const RemanenceRecognition *recognition,
                                    size_t verdict,
                                    size_t location,
                                    RemanenceLocationVerdict *out);

// The member one position was read from, or null when out of range.
const char *remanence_recognition_location_artifact(const RemanenceRecognition *recognition,
                                                    size_t verdict,
                                                    size_t location);

// Why a position was not claimed, in the profile's own terms; null when
// it was claimed or the index is out of range.
const char *remanence_recognition_location_refusal(const RemanenceRecognition *recognition,
                                                   size_t verdict,
                                                   size_t location);

// Plans the reduction of a capture set to one 1541 flux medium.
// Nothing is written and nothing is mutated. Returns null on failure
// and stores a message in `error_out` (free with
// `remanence_string_free`).
RemanenceMasteringPlan *remanence_capture_set_plan_c1541_mastering(const RemanenceCaptureSet *set,
                                                                   const RemanenceMasteringPolicy *policy,
                                                                   RemanenceErrorCategory *error_category_out,
                                                                   char **error_out,
                                                                   char **error_rule_out);

// Frees a plan handle.
void remanence_mastering_plan_free(RemanenceMasteringPlan *plan);

// Produces the medium the plan described, consuming the plan: the
// handle is freed whether this succeeds or fails, and must not be used
// again. Returns null on failure.
RemanenceMasteredMedium *remanence_mastering_plan_execute(RemanenceMasteringPlan *plan,
                                                          uint64_t cache_bytes,
                                                          RemanenceErrorCategory *error_category_out,
                                                          char **error_out,
                                                          char **error_rule_out);

// Frees a mastered-medium handle, discarding its private session
// storage.
void remanence_mastered_medium_free(RemanenceMasteredMedium *medium);

// How many locations the medium claims.
uint64_t remanence_mastered_medium_locations(const RemanenceMasteredMedium *medium);

// How many bytes of private session storage the medium occupies, and
// how much of that is currently resident.
uint64_t remanence_mastered_medium_backing_bytes(const RemanenceMasteredMedium *medium);

uint64_t remanence_mastered_medium_resident_bytes(const RemanenceMasteredMedium *medium);

// The profile the reduction was declared by. Pass whichever handle you
// hold and null for the other.
const char *remanence_mastering_profile_id(const RemanenceMasteringPlan *plan,
                                           const RemanenceMasteredMedium *medium);

// The frame the medium is expressed in.
uint64_t remanence_mastering_reference_clock_hz(const RemanenceMasteringPlan *plan,
                                                const RemanenceMasteredMedium *medium);

uint64_t remanence_mastering_cycles_per_rotation(const RemanenceMasteringPlan *plan,
                                                 const RemanenceMasteredMedium *medium);

// Which rule placed the circle's origin.
const char *remanence_mastering_origin_rule(const RemanenceMasteringPlan *plan,
                                            const RemanenceMasteredMedium *medium);

// How many half-tracks the reduction produces.
size_t remanence_mastering_location_count(const RemanenceMasteringPlan *plan,
                                          const RemanenceMasteredMedium *medium);

// One of them, written into `out`. Returns false when out of range.
bool remanence_mastering_location(const RemanenceMasteringPlan *plan,
                                  const RemanenceMasteredMedium *medium,
                                  size_t index,
                                  RemanenceMasteredLocation *out);

// How many kinds of loss the destination will not carry.
size_t remanence_mastering_declared_loss_count(const RemanenceMasteringPlan *plan,
                                               const RemanenceMasteredMedium *medium);

// One loss entry's stable code, or null when out of range.
const char *remanence_mastering_declared_loss_code(const RemanenceMasteringPlan *plan,
                                                   const RemanenceMasteredMedium *medium,
                                                   size_t index);

// What was lost, in the source's own terms. A count is not an account.
const char *remanence_mastering_declared_loss_detail(const RemanenceMasteringPlan *plan,
                                                     const RemanenceMasteredMedium *medium,
                                                     size_t index);

// How much of it there was, in whatever the detail counts.
uint64_t remanence_mastering_declared_loss_amount(const RemanenceMasteringPlan *plan,
                                                  const RemanenceMasteredMedium *medium,
                                                  size_t index);

// The policy that produced the plan, stated in full.
size_t remanence_mastering_evidence_count(const RemanenceMasteringPlan *plan,
                                          const RemanenceMasteredMedium *medium);

const char *remanence_mastering_evidence(const RemanenceMasteringPlan *plan,
                                         const RemanenceMasteredMedium *medium,
                                         size_t index);

// Opens the P64 image at `path` (UTF-8), claiming the file and decoding
// every half-track once into private session storage. The version is
// checked before anything else is touched, and a version, flag bit, or
// chunk signature past this release's claim is refused by name. Returns
// null on failure and stores a message in `error_out` (free with
// `remanence_string_free`).
RemanenceP64Image *remanence_p64_image_open(const char *path,
                                            RemanenceErrorCategory *error_category_out,
                                            char **error_out,
                                            char **error_rule_out);

// Opens a P64 image as `remanence_p64_image_open` does, under a
// declared cache bound: at most `cache_bytes` of the decoded medium
// stays resident. The bound narrows the working set; it never refuses
// service.
RemanenceP64Image *remanence_p64_image_open_with_cache(const char *path,
                                                       uint64_t cache_bytes,
                                                       RemanenceErrorCategory *error_category_out,
                                                       char **error_out,
                                                       char **error_rule_out);

// Frees an image handle, releasing its claim on the file and discarding
// the private session storage the medium decoded into.
void remanence_p64_image_free(RemanenceP64Image *image);

// The path the image was opened from.
const char *remanence_p64_image_path(const RemanenceP64Image *image);

// Which P7 mode the open obtained on the file.
RemanenceAccessMode remanence_p64_image_access_mode(const RemanenceP64Image *image);

// How many bytes of private session storage the decoded medium
// occupies, and how much of that is currently resident.
uint64_t remanence_p64_image_backing_bytes(const RemanenceP64Image *image);

uint64_t remanence_p64_image_resident_bytes(const RemanenceP64Image *image);

// Computes what a P64 will and will not carry of a mastered medium,
// writing nothing. Read it before writing: the write adds nothing to
// the account. Returns null on failure.
RemanenceP64Report *remanence_mastered_medium_describe_p64(const RemanenceMasteredMedium *medium,
                                                           RemanenceErrorCategory *error_category_out,
                                                           char **error_out,
                                                           char **error_rule_out);

// Writes a mastered medium into a new P64 image at `path` (UTF-8) and
// reports what the container carried. The medium is untouched, an
// existing destination is a named refusal rather than an overwrite, and
// an interruption leaves the destination absent rather than half an
// artifact. Returns null on failure.
RemanenceP64Report *remanence_mastered_medium_write_p64(const RemanenceMasteredMedium *medium,
                                                        const char *path,
                                                        RemanenceErrorCategory *error_category_out,
                                                        char **error_out,
                                                        char **error_rule_out);

// Frees a report handle.
void remanence_p64_report_free(RemanenceP64Report *report);

// The container format's stable identifier, "p64".
const char *remanence_p64_format_id(const RemanenceP64Image *image,
                                    const RemanenceP64Report *report);

const char *remanence_p64_format_name(const RemanenceP64Image *image,
                                      const RemanenceP64Report *report);

// The container's declared format version.
uint32_t remanence_p64_version(const RemanenceP64Image *image, const RemanenceP64Report *report);

bool remanence_p64_write_protected(const RemanenceP64Image *image,
                                   const RemanenceP64Report *report);

bool remanence_p64_double_sided(const RemanenceP64Image *image, const RemanenceP64Report *report);

// The drive profile the container's own signature names, and the frame
// that profile declares.
const char *remanence_p64_profile_id(const RemanenceP64Image *image,
                                     const RemanenceP64Report *report);

uint64_t remanence_p64_reference_clock_hz(const RemanenceP64Image *image,
                                          const RemanenceP64Report *report);

uint64_t remanence_p64_cycles_per_rotation(const RemanenceP64Image *image,
                                           const RemanenceP64Report *report);

// How many half-tracks the container holds.
size_t remanence_p64_half_track_count(const RemanenceP64Image *image,
                                      const RemanenceP64Report *report);

// One of them, written into `out`. Returns false when out of range.
bool remanence_p64_half_track(const RemanenceP64Image *image,
                              const RemanenceP64Report *report,
                              size_t index,
                              RemanenceP64HalfTrack *out);

// How many kinds of loss the crossing does not carry.
size_t remanence_p64_declared_loss_count(const RemanenceP64Image *image,
                                         const RemanenceP64Report *report);

// One loss entry's stable code, or null when out of range.
const char *remanence_p64_declared_loss_code(const RemanenceP64Image *image,
                                             const RemanenceP64Report *report,
                                             size_t index);

// What was lost, in the source's own terms. A count is not an account.
const char *remanence_p64_declared_loss_detail(const RemanenceP64Image *image,
                                               const RemanenceP64Report *report,
                                               size_t index);

// How much of it there was, in whatever the detail counts.
uint64_t remanence_p64_declared_loss_amount(const RemanenceP64Image *image,
                                            const RemanenceP64Report *report,
                                            size_t index);

// How the container was recognized and what this adapter claims of it.
size_t remanence_p64_evidence_count(const RemanenceP64Image *image,
                                    const RemanenceP64Report *report);

const char *remanence_p64_evidence(const RemanenceP64Image *image,
                                   const RemanenceP64Report *report,
                                   size_t index);

// Inspects an open disk and returns its layered report. Null on failure,
// with the category and message written to the out-parameters.
RemanenceDiskReport *remanence_disk_inspect(RemanenceDisk *disk,
                                            RemanenceErrorCategory *error_category_out,
                                            char **error_out,
                                            char **error_rule_out);

// Frees an inspection report and everything borrowed from it.
void remanence_disk_report_free(RemanenceDiskReport *report);

// The device identity assigned by this loaded composition (P21), scoped
// to the open.
uint64_t remanence_report_device_id(const RemanenceDiskReport *report);

// The image format the container turned out to be.
const char *remanence_report_device_image_format(const RemanenceDiskReport *report);

// The device's addressable length in bytes.
uint64_t remanence_report_device_length_bytes(const RemanenceDiskReport *report);

// The layer the image is authoritative at (P13).
const char *remanence_report_device_authoritative_layer(const RemanenceDiskReport *report);

// The layer active for this composition (P23).
const char *remanence_report_device_active_layer(const RemanenceDiskReport *report);

// What the device's leading structure turned out to be.
RemanenceDiskContent remanence_report_content(const RemanenceDiskReport *report);

// Why no adapter claimed the content, for the unknown-nonblank outcome;
// null for every other outcome.
const char *remanence_report_content_evidence(const RemanenceDiskReport *report);

// Whether a partition schema was recognized.
bool remanence_report_has_partition_schema(const RemanenceDiskReport *report);

// The recognized schema's kind, or null where none was recognized.
const char *remanence_report_partition_schema_kind(const RemanenceDiskReport *report);

// How many evidence lines the schema recognition carries.
size_t remanence_report_partition_schema_evidence_count(const RemanenceDiskReport *report);

// One evidence line from the schema recognition.
const char *remanence_report_partition_schema_evidence(const RemanenceDiskReport *report,
                                                       size_t index);

// How many regions the schema declares. Every declared region is
// reported, refused ones included.
size_t remanence_report_region_count(const RemanenceDiskReport *report);

// A region's opaque identity. Pass it back to the library; never parse
// it, and never build one.
uint64_t remanence_report_region_id(const RemanenceDiskReport *report, size_t index);

// The number the schema itself declared this region at.
uint32_t remanence_report_region_declared_number(const RemanenceDiskReport *report, size_t index);

// How the schema places this region in its own vocabulary: for MBR,
// "primary" for one of the four slots and "logical" for an entry on the
// extended chain. A different axis from the role: the extended container
// is a primary slot whose role is structural.
const char *remanence_report_region_declared_placement(const RemanenceDiskReport *report,
                                                       size_t index);

// Whether the schema declares this region as data or as structure.
RemanenceRegionRole remanence_report_region_role(const RemanenceDiskReport *report, size_t index);

// The type value exactly as the schema records it.
uint8_t remanence_report_region_declared_type(const RemanenceDiskReport *report, size_t index);

// What that value declares, in a sentence fit to quote in a refusal.
// Present whether or not this release reads the type, and it describes
// the declaration rather than the content.
const char *remanence_report_region_declared_type_reading(const RemanenceDiskReport *report,
                                                          size_t index);

// Whether this release reads the declared type.
bool remanence_report_region_is_claimed(const RemanenceDiskReport *report, size_t index);

// Where the region starts, in bytes.
uint64_t remanence_report_region_start_bytes(const RemanenceDiskReport *report, size_t index);

// How long the region is, in bytes.
uint64_t remanence_report_region_length_bytes(const RemanenceDiskReport *report, size_t index);

// The region's refusal category; false where the region reads cleanly.
bool remanence_report_region_issue_category(const RemanenceDiskReport *report,
                                            size_t index,
                                            RemanenceErrorCategory *category_out);

// The region's refusal, or null where the region reads cleanly.
const char *remanence_report_region_issue(const RemanenceDiskReport *report, size_t index);

// How many volumes were composed, whatever was recognized on them.
size_t remanence_report_volume_count(const RemanenceDiskReport *report);

// How many volumes carry a filesystem the host actually read. Distinct
// from the composed count on purpose: an unrecognized volume stays in the
// report rather than vanishing to keep one number correct.
size_t remanence_report_readable_filesystem_volume_count(const RemanenceDiskReport *report);

// A volume's opaque identity.
uint64_t remanence_report_volume_id(const RemanenceDiskReport *report, size_t index);

// What this volume was composed from.
RemanenceVolumeOrigin remanence_report_volume_origin(const RemanenceDiskReport *report,
                                                     size_t index);

// How many regions this volume was composed from; 0 for a whole-device
// volume.
size_t remanence_report_volume_origin_region_count(const RemanenceDiskReport *report, size_t index);

// The identity of one region this volume was composed from.
uint64_t remanence_report_volume_origin_region_id(const RemanenceDiskReport *report,
                                                  size_t index,
                                                  size_t region_index);

// Where the volume starts, in bytes.
uint64_t remanence_report_volume_start_bytes(const RemanenceDiskReport *report, size_t index);

// How long the volume is, in bytes.
uint64_t remanence_report_volume_length_bytes(const RemanenceDiskReport *report, size_t index);

// How many evidence lines this volume's composition carries.
size_t remanence_report_volume_evidence_count(const RemanenceDiskReport *report, size_t index);

// One evidence line from this volume's composition.
const char *remanence_report_volume_evidence(const RemanenceDiskReport *report,
                                             size_t index,
                                             size_t evidence_index);

// How many volumes filesystem recognition was attempted on. A refused
// attempt is recorded here, at the seam that owns the refusal.
size_t remanence_report_filesystem_count(const RemanenceDiskReport *report);

// A filesystem's opaque identity.
uint64_t remanence_report_filesystem_id(const RemanenceDiskReport *report, size_t index);

// The identity of the volume this recognition was attempted on.
uint64_t remanence_report_filesystem_volume_id(const RemanenceDiskReport *report, size_t index);

// The recognized filesystem kind, or null where recognition was refused —
// the issue then says why, and the volume still stands.
const char *remanence_report_filesystem_kind(const RemanenceDiskReport *report, size_t index);

// Whether a filesystem answered the label question at all. False where
// recognition was refused — there is then no filesystem to answer, which
// is not the same as a volume that answered "unlabeled".
bool remanence_report_filesystem_label_answered(const RemanenceDiskReport *report, size_t index);

// The volume label, or null where the volume has none — the format's own
// spelling of unlabeled already resolved, so no caller compares strings
// to find that out. Null also where nothing answered;
// `remanence_report_filesystem_label_answered` tells the two apart.
const char *remanence_report_filesystem_label(const RemanenceDiskReport *report, size_t index);

// Which source decided the answer, or null where the volume carries no
// such source at all. A source that exists and says unlabeled is named
// here beside a null label.
const char *remanence_report_filesystem_label_answered_by(const RemanenceDiskReport *report,
                                                          size_t index);

// How many sources this filesystem read for the label, kept beside the
// answer as evidence (P4).
size_t remanence_report_filesystem_label_reading_count(const RemanenceDiskReport *report,
                                                       size_t index);

// One source's name, in the recognizing filesystem's own vocabulary.
const char *remanence_report_filesystem_label_reading_source(const RemanenceDiskReport *report,
                                                             size_t index,
                                                             size_t reading_index);

// Whether the format gives this volume that field at all. False is the
// third state — no such field — and is distinct from a field that is
// present and blank.
bool remanence_report_filesystem_label_reading_present(const RemanenceDiskReport *report,
                                                       size_t index,
                                                       size_t reading_index);

// What that source holds, as stored and less the format's own
// fixed-width padding: the empty string where it is present and blank,
// and null where there is no such field.
const char *remanence_report_filesystem_label_reading_stored(const RemanenceDiskReport *report,
                                                             size_t index,
                                                             size_t reading_index);

// The allocation unit size, where the filesystem states one.
bool remanence_report_filesystem_cluster_bytes(const RemanenceDiskReport *report,
                                               size_t index,
                                               uint64_t *value_out);

// The allocation unit count, where the filesystem states one.
bool remanence_report_filesystem_cluster_count(const RemanenceDiskReport *report,
                                               size_t index,
                                               uint64_t *value_out);

// Sectors per track as the filesystem's own structures declare it. A
// filesystem declaration, which manufactures no physical drive.
bool remanence_report_filesystem_sectors_per_track(const RemanenceDiskReport *report,
                                                   size_t index,
                                                   uint16_t *value_out);

// Heads as the filesystem's own structures declare it.
bool remanence_report_filesystem_heads(const RemanenceDiskReport *report,
                                       size_t index,
                                       uint16_t *value_out);

// Cylinders, only where the derivation is exact. Never invented.
bool remanence_report_filesystem_cylinders(const RemanenceDiskReport *report,
                                           size_t index,
                                           uint64_t *value_out);

// How many issues this recognition carries.
size_t remanence_report_filesystem_issue_count(const RemanenceDiskReport *report, size_t index);

// One issue's stable category.
bool remanence_report_filesystem_issue_category(const RemanenceDiskReport *report,
                                                size_t index,
                                                size_t issue_index,
                                                RemanenceErrorCategory *category_out);

// One issue's diagnostic.
const char *remanence_report_filesystem_issue(const RemanenceDiskReport *report,
                                              size_t index,
                                              size_t issue_index);

// How many DOS assignment rules this release claims (P3).
size_t remanence_dos_rule_count(void);

// One claimed rule's stable name — the value passed to
// `remanence_dos_machine_compose`. Null when the index is out of range.
const char *remanence_dos_rule_name(size_t index);

// What that rule says, in a sentence fit to show a user beside the
// mapping it produced.
const char *remanence_dos_rule_reading(size_t index);

// A machine with nothing asserted about it yet. Free with
// `remanence_dos_machine_free`.
RemanenceDosMachine *remanence_dos_machine_new(void);

// Frees a machine and the reports it copied.
void remanence_dos_machine_free(RemanenceDosMachine *machine);

// Asserts that the medium `report` inspects occupies floppy slot `slot` —
// 0 being `A:`. A slot above 1 and a slot already asserted are refused by
// name. The report is copied; the handle may be freed afterwards.
bool remanence_dos_machine_assert_floppy(RemanenceDosMachine *machine,
                                         uint32_t slot,
                                         const RemanenceDiskReport *report,
                                         RemanenceErrorCategory *error_category_out,
                                         char **error_out,
                                         char **error_rule_out);

// Asserts that the medium `report` inspects is the fixed disk attached at
// `order` — 0 being the first attached, which is the order DOS assigned
// letters in.
bool remanence_dos_machine_assert_fixed_disk(RemanenceDosMachine *machine,
                                             uint32_t order,
                                             const RemanenceDiskReport *report,
                                             RemanenceErrorCategory *error_category_out,
                                             char **error_out,
                                             char **error_rule_out);

// Asserts a CD-ROM drive at attachment order `order`. `driver_letter` is
// where the caller declares the resident driver placed it; `0` declares
// no placement, and an undeclared CD-ROM takes no letter rather than a
// guessed one.
bool remanence_dos_machine_assert_cdrom(RemanenceDosMachine *machine,
                                        uint32_t order,
                                        char driver_letter,
                                        RemanenceErrorCategory *error_category_out,
                                        char **error_out,
                                        char **error_rule_out);

// Declares a runtime condition outside every claimed rule, by its stable
// spelling: `lastdrive=<letter>`, `subst`, `join`, `assign`,
// `block-device-driver`, `network-redirector`. Anything else is refused by
// name. The letters the condition could have changed come back
// undetermined.
bool remanence_dos_machine_declare_condition(RemanenceDosMachine *machine,
                                             const char *condition,
                                             RemanenceErrorCategory *error_category_out,
                                             char **error_out,
                                             char **error_rule_out);

// Composes the mapping. `rule` names the variant the machine ran — one of
// `remanence_dos_rule_name` — or is null where the caller states none, in
// which case every claimed rule is applied and a letter they disagree on
// comes back undetermined. Null on failure, with the category and message
// written to the out-parameters.
RemanenceDriveMap *remanence_dos_machine_compose(const RemanenceDosMachine *machine,
                                                 const char *rule,
                                                 RemanenceErrorCategory *error_category_out,
                                                 char **error_out,
                                                 char **error_rule_out);

// Frees a composed mapping and everything borrowed from it.
void remanence_drive_map_free(RemanenceDriveMap *map);

// How many rules were applied: one where the caller stated the variant,
// and every claimed rule where it did not.
size_t remanence_drive_map_applied_rule_count(const RemanenceDriveMap *map);

// One applied rule's stable name.
const char *remanence_drive_map_applied_rule(const RemanenceDriveMap *map, size_t index);

// How many letters the machine had a drive at. A letter absent from the
// mapping is a letter the machine had no drive at, which is different from
// one that exists and could not be settled.
size_t remanence_drive_map_count(const RemanenceDriveMap *map);

// How many letters the rules established — the count that excludes every
// undetermined one.
size_t remanence_drive_map_established_count(const RemanenceDriveMap *map);

// The letter at `index`, without its colon. `0` when out of range.
char remanence_drive_map_letter(const RemanenceDriveMap *map, size_t index);

// Finds the entry for one letter, writing its index. False where the
// machine had no drive at that letter.
bool remanence_drive_map_find(const RemanenceDriveMap *map, char letter, size_t *index_out);

// What the letter at `index` turned out to name.
RemanenceLetterOutcome remanence_drive_map_outcome(const RemanenceDriveMap *map, size_t index);

// The asserted device this letter names — `floppy`, `fixed-disk` or
// `cd-rom` — or null where the outcome names no device.
const char *remanence_drive_map_device_kind(const RemanenceDriveMap *map, size_t index);

// The slot or attachment order the caller asserted for that device.
bool remanence_drive_map_device_index(const RemanenceDriveMap *map,
                                      size_t index,
                                      uint32_t *value_out);

// The volume this letter names, by the identity its own inspection report
// issued — the value passed back into a file verb. False where the
// outcome names no volume.
bool remanence_drive_map_volume(const RemanenceDriveMap *map, size_t index, uint64_t *value_out);

// The letter a phantom drive stands for, or `0` where this outcome is not
// a phantom.
char remanence_drive_map_phantom_of(const RemanenceDriveMap *map, size_t index);

// Why the claimed rules could not settle this letter, or null where they
// did.
const char *remanence_drive_map_reason(const RemanenceDriveMap *map, size_t index);

// How many provenance lines the mapping carries.
size_t remanence_drive_map_provenance_count(const RemanenceDriveMap *map);

// One provenance line: the asserted facts and the applied rules,
// travelling with the answer. **This is not evidence** — nothing in it was
// read off a disk.
const char *remanence_drive_map_provenance(const RemanenceDriveMap *map, size_t index);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* REMANENCE_H */
