# SPDX-FileCopyrightText: 2026 Paul Galbraith
# SPDX-License-Identifier: GPL-3.0-only

"""Type stubs for the Remanence Python module (S3).

The stub is the surface written down. Every class, property and verb the
module registers appears here exactly once, and a disagreement between
this file and `crates/remanence-py/src/lib.rs` is a bug in one of them —
the module is the norm, so the stub is what moves.

Values that cross the boundary as stable spellings — a format id, a
device type, an article, a rule identity — are typed `str` rather than a
`Literal` union: the claim is enumerated at runtime by `formats()`,
`device_slots()`, `partition_types()` and their kin, and freezing those
sets into the stub would put a second, staler claim beside the one the
library answers with.
"""

import os
from typing import IO, final

__version__: str

DEFAULT_CACHE_BYTES: int
"""The per-medium session cache bound a load takes when none is stated."""

class Error(Exception):
    """Every refusal the library makes (P3, P10).

    Both attributes below are set on every instance, so they are safe to
    read in an `except` block without `getattr`.
    """

    category: str
    """How to behave. Always set."""

    rule: str | None
    """Which rule of an enumerated set the input broke.

    `None` where the refusal belongs to no such set, which is the
    ordinary case rather than an omission.
    """

_OpenFile = IO[bytes] | int
"""An artifact the caller opened: a binary file object, or its descriptor.

Whoever opens owns the lock (P7) — the library checks the handle for one
thing only (may it write?) and takes no lock of its own.
"""

MediaSource = _OpenFile | FileSource | list[_OpenFile] | list[FileSource]
"""The four shapes a load's source takes.

One opened artifact, a collection of them, one `FileSource` taken from
another medium's namespace, or a collection of those. A collection is
one kind throughout: its first member says which, and a member of the
other kind is refused by name.
"""

_Path = str | os.PathLike[str]

# --------------------------------------------------------------- catalogs

def formats() -> list[tuple[str, str, list[str], bool, bool]]:
    """Every format this release claims.

    Each entry is `(id, name, device_types, takes_block_bytes,
    takes_collection)`. A format that records several device types needs
    one declared at the load; one that records a single device carries it
    already.
    """

def new_media_kinds() -> list[tuple[str, str, str, bool]]:
    """Every authored-media kind: `(id, name, article, takes_geometry)`."""

def device_slots() -> list[DeviceSlot]:
    """Every device slot a machine can be given, and the archive receiver."""

def partition_schemes() -> list[tuple[str, str]]:
    """Every partition scheme this release reads: `(id, name)`."""

def partition_types() -> list[tuple[str, str]]:
    """Every partition type a caller may declare: `(id, name)`."""

def dos_assignment_rules() -> list[DosAssignmentRule]:
    """Every DOS drive-letter assignment rule this release claims."""

def geometry_sources() -> list[str]:
    """Every source a geometry reading can be attributed to."""

def assurance_conditions() -> list[str]:
    """Every assurance condition this release claims (P3)."""

# -------------------------------------------------------------- discovery

def discover_media(path: _Path, *, writable: bool) -> Discovery:
    """Answers *what is this?* on no handle at all.

    Opens the artifact by name — so P7's mandatory denial applies in
    full — and builds no cache: no medium, no session cache, no spilled
    backing, because a cache bound is the load's declaration (P27).
    """

@final
class Discovery:
    """What an artifact turned out to be, and the claim over it.

    Consumed by `Session.load_discovery`, so nothing runs twice; reading
    a consumed discovery is refused by name.
    """

    @property
    def path(self) -> str | None: ...
    @property
    def image_path(self) -> str | None: ...
    @property
    def image_format(self) -> str: ...
    @property
    def image_format_name(self) -> str: ...
    @property
    def format(self) -> str: ...
    @property
    def article(self) -> str: ...
    @property
    def article_name(self) -> str: ...
    @property
    def accepting_devices(self) -> list[str]:
        """The device families that would take this medium."""

    @property
    def device_type(self) -> str | None:
        """The one device the format records, or `None` where it records several."""

    @property
    def device_types(self) -> list[str]: ...
    @property
    def image_size_bytes(self) -> int: ...
    @property
    def size(self) -> int: ...
    @property
    def mode(self) -> str: ...
    @property
    def assurance(self) -> Assurance: ...
    def identify(self) -> Identification: ...
    def __repr__(self) -> str: ...

# ----------------------------------------------------------- the session

@final
class Session:
    """The pool of machines (configuration) and media (state)."""

    def __init__(self) -> None: ...
    def load_media(
        self,
        source: MediaSource,
        format: str,
        *,
        device: str | None = None,
        block_bytes: int | None = None,
        cache_bytes: int | None = None,
    ) -> Medium:
        """The declared reading: one source and one concrete format.

        `device` is stated where the format records several and refused
        where it records one.
        """

    def new_media(
        self,
        kind: str,
        *,
        cylinders: int | None = None,
        heads: int | None = None,
        sectors_per_track: int | None = None,
        sector_bytes: int | None = None,
        cache_bytes: int | None = None,
    ) -> Medium:
        """Creates blank media whole — authorship, the third fact class.

        The coordinates are the author's own, for the kind whose claim
        takes them; a blank article kind takes none and refuses them.
        """

    def load_discovery(
        self, discovery: Discovery, *, cache_bytes: int | None = None
    ) -> Medium: ...
    def load_discovery_as(
        self, discovery: Discovery, device: str, *, cache_bytes: int | None = None
    ) -> Medium: ...
    @property
    def media(self) -> list[int]: ...
    def medium(self, media_id: int, /) -> Medium | None: ...
    def release_media(self, media_id: int, /) -> None:
        """The one state-destroying verb."""

    def add_machine(self, identity: str, /) -> Machine: ...
    @property
    def machines(self) -> list[str | None]: ...
    def machine(self, identity: str | None = None, /) -> Machine | None: ...
    def release_machine(self, identity: str, /) -> None: ...
    def add_device(self, device: str, *, slot: int | None = None) -> StorageDevice: ...
    def add_device_for(
        self, path: _Path, *, writable: bool, cache_bytes: int | None = None
    ) -> StorageDevice: ...
    @property
    def devices(self) -> list[str]: ...
    def device(self, attachment: str, /) -> StorageDevice | None: ...
    def release_device(self, attachment: str, /) -> None: ...
    def __enter__(self) -> Session: ...
    def __exit__(self, exc_type: object, exc: object, tb: object, /) -> bool: ...

@final
class Machine:
    """One machine's configuration: the devices it held."""

    @property
    def identity(self) -> str | None: ...
    def add_device(self, device: str, *, slot: int | None = None) -> StorageDevice: ...
    def add_device_for(
        self, path: _Path, *, writable: bool, cache_bytes: int | None = None
    ) -> StorageDevice: ...
    @property
    def devices(self) -> list[str]: ...
    def device(self, attachment: str, /) -> StorageDevice | None: ...
    def release_device(self, attachment: str, /) -> None: ...
    def compose_dos_letters(self, rule: str | None = None, /) -> DriveMap: ...

@final
class StorageDevice:
    """One device slot, and whatever medium occupies it."""

    @property
    def attachment(self) -> str: ...
    @property
    def slot_prefix(self) -> str: ...
    @property
    def slot(self) -> str: ...
    @property
    def device_type(self) -> str | None: ...
    @property
    def is_occupied(self) -> bool: ...
    @property
    def media_id(self) -> int | None: ...
    @property
    def medium(self) -> Medium | None: ...
    def insert(self, media_id: int, /) -> None:
        """Links a pooled medium in by device-type equality.

        A medium another device recorded is refused, naming both sides.
        """

    def eject(self) -> int:
        """Severs only: the claim and everything buffered survive in the pool."""

@final
class DeviceSlot:
    """One slot a machine can be given, as the catalog states it."""

    @property
    def id(self) -> str: ...
    @property
    def name(self) -> str: ...
    @property
    def device_type(self) -> str | None: ...
    @property
    def device_class(self) -> str | None: ...
    @property
    def provenance(self) -> str | None: ...
    @property
    def article(self) -> str | None: ...
    @property
    def slot_prefix(self) -> str: ...
    @property
    def flux_path(self) -> str | None: ...
    @property
    def scheme(self) -> str | None: ...
    @property
    def addressing(self) -> str | None: ...
    def __repr__(self) -> str: ...

# ---------------------------------------------------------------- medium

@final
class Medium:
    """The content handle: everything a recording can answer, answers here."""

    @property
    def id(self) -> int: ...
    @property
    def is_linked(self) -> bool: ...
    @property
    def article(self) -> str: ...
    @property
    def device_type(self) -> str | None:
        """`None` for an authored blank, which assumes no device."""

    @property
    def authored_as(self) -> str | None: ...
    @property
    def path(self) -> str | None: ...
    @property
    def image_path(self) -> str | None: ...
    @property
    def image_size_bytes(self) -> int: ...
    @property
    def size(self) -> int: ...
    @property
    def mode(self) -> str: ...
    @property
    def format(self) -> str: ...
    @property
    def qcow2_version(self) -> int | None: ...
    @property
    def vdi_version(self) -> tuple[int, int] | None: ...
    @property
    def is_modified(self) -> bool: ...
    @property
    def assurance(self) -> Assurance:
        """What the open established about the evidence beneath it (P28)."""

    @property
    def geometry(self) -> Geometry:
        """What the sources beneath the medium stated about the coordinates."""

    def identify(self) -> Identification:
        """The layers of the artifact's nesting, over the image's own bytes."""

    def inspect(self) -> DiskReport:
        """The disk a format adapter presents above those layers."""

    def read_at(self, offset: int, length: int, /) -> bytes: ...
    def read_sector(self, cylinder: int, head: int, sector: int, /) -> bytes:
        """Addresses in the discovered geometry.

        Refused by name — its own `GeometryRule` set — on types whose
        recording is not sector-addressed.
        """

    def write_sector(
        self, cylinder: int, head: int, sector: int, data: bytes, /
    ) -> None:
        """Buffers until `commit`, like every other write."""

    @property
    def partition_scheme(self) -> str | None:
        """The scheme the pool was populated under, established at the load."""

    def partitions(self) -> list[Partition]: ...
    def partition(self, ordinal: int, /) -> Partition | None:
        """By the scheme's own ordinal.

        A medium recording no scheme bears the direct partition at 0.
        """

    def bitstream(self) -> C1541Bitstream:
        """Clocks the family's pulses under the profile's declared channel."""

    def bytestream(self) -> C1541Bytestream:
        """Resolves the bitstream under the family's declared group code."""

    def commit(self) -> None: ...
    def rollback(self) -> None: ...

@final
class Partition:
    """One member of the scheme, or the library's own direct composition."""

    @property
    def ordinal(self) -> int: ...
    @property
    def is_direct(self) -> bool:
        """The library's own composition of the whole content.

        Carried as provenance and never as evidence: a medium recording
        no scheme bears it at ordinal 0.
        """

    @property
    def active(self) -> bool:
        """Whether the scheme flags it active."""

    @property
    def type_byte(self) -> int | None:
        """The raw recorded value. `None` for the direct partition."""

    @property
    def type_reading(self) -> str | None:
        """What that value declares."""

    @property
    def is_claimed(self) -> bool: ...
    @property
    def placement(self) -> str: ...
    @property
    def role(self) -> str: ...
    @property
    def start_bytes(self) -> int | None: ...
    @property
    def length_bytes(self) -> int | None: ...
    @property
    def is_addressable(self) -> bool: ...
    @property
    def bears_namespace(self) -> bool: ...
    @property
    def volume_id(self) -> int | None: ...
    @property
    def issue_category(self) -> str | None: ...
    @property
    def issue(self) -> str | None: ...
    @property
    def evidence(self) -> list[str]: ...
    @property
    def provenance(self) -> str | None: ...
    def check_type(self, type_id: str, /) -> None:
        """The caller's reading, checked against the recorded byte.

        The refusal is the whole of its value: a reading the byte does
        not bear is refused naming both sides, and the direct partition
        records no type to check against.
        """

    def volume(self) -> StorageSpace | None: ...
    def filesystem(self) -> StorageSpace | None: ...
    def filesystem_as(self, id: str, /) -> StorageSpace:
        """The caller's reading where no partition type determines one."""

    def __repr__(self) -> str: ...

@final
class StorageSpace:
    """The one node file access lives on."""

    @property
    def is_addressable(self) -> bool: ...
    @property
    def volume_id(self) -> int | None: ...
    @property
    def start_bytes(self) -> int | None: ...
    @property
    def length_bytes(self) -> int | None: ...
    @property
    def has_namespace(self) -> bool: ...
    @property
    def kind(self) -> str | None: ...
    def read_at(self, offset: int, length: int, /) -> bytes: ...
    def write_at(self, offset: int, data: bytes, /) -> None: ...
    def label(self) -> VolumeLabel | None: ...
    def evidence(self) -> list[str]: ...
    def entries(self, path: str = "", /) -> list[Entry]: ...
    def files(self, path: str = "", /) -> list[FileSource]: ...
    def stat(self, path: str, /) -> Entry | None: ...
    def get_file(self, path: str, /) -> File: ...
    def read_file(self, path: str, /) -> bytes: ...
    def write_file(self, path: str, contents: bytes, /) -> None: ...
    def resize_file(self, path: str, size: int, /) -> None: ...
    def make_directory(self, path: str, /) -> None: ...
    def __repr__(self) -> str: ...

@final
class File:
    """One file in a namespace, opened by name."""

    @property
    def path(self) -> str: ...
    @property
    def name(self) -> str: ...
    @property
    def size_bytes(self) -> int: ...
    @property
    def entry(self) -> Entry: ...
    def bytes(self) -> bytes: ...
    def read_at(self, offset: int, length: int, /) -> bytes: ...
    def write_at(self, offset: int, data: bytes, /) -> None: ...
    def discover(self) -> Discovery:
        """An entry recognized as an artifact of its own — the one recursion."""

    def source(self) -> FileSource: ...
    def __repr__(self) -> str: ...

@final
class FileSource:
    """One file taken from another medium's namespace, as a load's source.

    Consumed on the way through a load, whether or not the load is then
    refused.
    """

    @property
    def name(self) -> str: ...
    @property
    def size_bytes(self) -> int: ...
    def __repr__(self) -> str: ...

@final
class Entry:
    @property
    def name(self) -> str: ...
    @property
    def kind(self) -> str: ...
    @property
    def size_bytes(self) -> int: ...
    @property
    def declared(self) -> list[EntryFact]: ...
    def __repr__(self) -> str: ...

@final
class EntryFact:
    @property
    def key(self) -> str: ...
    @property
    def value(self) -> str: ...
    def __repr__(self) -> str: ...

# ------------------------------------------------------ assurance, geometry

@final
class Assurance:
    """What an open established about the evidence beneath it (P28)."""

    @property
    def outcome(self) -> str: ...
    @property
    def condition(self) -> str | None: ...
    @property
    def evidence(self) -> list[str]: ...
    @property
    def readable(self) -> list[tuple[int, int]]: ...
    @property
    def access(self) -> str: ...
    @property
    def claim(self) -> str:
        """Whose open the P7 claim is: the library's, the caller's, or nobody's."""

    @property
    def declared_bytes(self) -> int | None: ...
    @property
    def observed_bytes(self) -> int | None: ...
    @property
    def first_unavailable_byte(self) -> int | None: ...
    def __repr__(self) -> str: ...

@final
class Geometry:
    """The recording's coordinates, with every reading that produced them.

    Sources that disagree settle nothing: the state is `undetermined`
    and both readings are carried.
    """

    @property
    def state(self) -> str: ...
    @property
    def cylinders(self) -> int | None: ...
    @property
    def heads(self) -> int | None: ...
    @property
    def sectors_per_track(self) -> int | None: ...
    @property
    def sector_bytes(self) -> int | None: ...
    @property
    def conflicts(self) -> list[str]: ...
    @property
    def unsettled(self) -> list[str]: ...
    @property
    def readings(self) -> list[GeometryReading]: ...
    def __repr__(self) -> str: ...

@final
class GeometryReading:
    @property
    def source(self) -> str: ...
    @property
    def at(self) -> str: ...
    @property
    def cylinders(self) -> int | None: ...
    @property
    def heads(self) -> int | None: ...
    @property
    def sectors_per_track(self) -> int | None: ...
    @property
    def sector_bytes(self) -> int | None: ...
    @property
    def detail(self) -> str: ...
    def __repr__(self) -> str: ...

# ------------------------------------------------------------ identification

@final
class Identification:
    @property
    def layers(self) -> list[Layer]: ...
    @property
    def modified(self) -> bool: ...
    @property
    def evidence(self) -> list[str]: ...

@final
class Layer:
    @property
    def kind(self) -> str: ...
    @property
    def id(self) -> str: ...
    @property
    def name(self) -> str: ...
    @property
    def confidence(self) -> int: ...
    @property
    def known(self) -> bool: ...
    @property
    def size(self) -> SizeInformation: ...
    @property
    def layout_kind(self) -> str: ...
    @property
    def layout(
        self,
    ) -> ArchiveLayout | ImageLayout | DiskLayout | FilesystemLayout | None:
        """Whichever layout `layout_kind` names, or `None` where none applies."""

@final
class SizeInformation:
    @property
    def current_bytes(self) -> int | None: ...
    @property
    def expected_bytes(self) -> int | None: ...

@final
class ArchiveLayout:
    @property
    def path(self) -> str | None: ...
    @property
    def entry_name(self) -> str: ...
    @property
    def compressed_size(self) -> int | None: ...
    @property
    def uncompressed_size(self) -> int | None: ...

@final
class ImageLayout:
    @property
    def payload_offset_bytes(self) -> int | None: ...
    @property
    def payload_length_bytes(self) -> int | None: ...

@final
class DiskLayout:
    @property
    def article(self) -> str: ...
    @property
    def sector_size(self) -> int | None: ...
    @property
    def cylinders(self) -> int | None: ...
    @property
    def sides(self) -> int | None: ...
    @property
    def sector_layout(self) -> str: ...
    @property
    def sectors_per_track(self) -> int | None: ...
    @property
    def tracks(self) -> list[TrackSectorLayout]: ...
    @property
    def total_sectors(self) -> int | None: ...

@final
class TrackSectorLayout:
    @property
    def cylinder(self) -> int: ...
    @property
    def side(self) -> int: ...
    @property
    def sectors(self) -> int: ...
    @property
    def sector_size(self) -> int | None: ...

@final
class FilesystemLayout:
    @property
    def offset_bytes(self) -> int | None: ...
    @property
    def length_bytes(self) -> int | None: ...

# ------------------------------------------------------------- inspection

@final
class DiskReport:
    """The disk a format adapter presents, and everything composed over it.

    List order is presentation only and never supplies identity: every
    relationship is traversed by the opaque identity the report issued.
    """

    @property
    def device(self) -> DeviceInfo: ...
    @property
    def content(self) -> str: ...
    @property
    def content_evidence(self) -> str | None: ...
    @property
    def partition_schema(self) -> PartitionSchemaInfo | None: ...
    @property
    def regions(self) -> list[RegionInfo]: ...
    @property
    def volumes(self) -> list[VolumeInfo]: ...
    @property
    def filesystems(self) -> list[FilesystemInfo]: ...
    def region(self, id: int, /) -> RegionInfo | None: ...
    def volume(self, id: int, /) -> VolumeInfo | None: ...
    def filesystem_on(self, volume: int, /) -> FilesystemInfo | None: ...
    def composed_volume_count(self) -> int: ...
    def readable_filesystem_volume_count(self) -> int: ...

@final
class DeviceInfo:
    @property
    def id(self) -> int: ...
    @property
    def image_format(self) -> str: ...
    @property
    def article(self) -> str: ...
    @property
    def device_type(self) -> str | None: ...
    @property
    def length_bytes(self) -> int: ...
    @property
    def authoritative_layer(self) -> str: ...
    @property
    def active_layer(self) -> str: ...

@final
class PartitionSchemaInfo:
    @property
    def kind(self) -> str: ...
    @property
    def evidence(self) -> list[str]: ...
    @property
    def issues(self) -> list[str]: ...

@final
class RegionInfo:
    @property
    def id(self) -> int: ...
    @property
    def declared_number(self) -> int: ...
    @property
    def declared_placement(self) -> str: ...
    @property
    def role(self) -> str: ...
    @property
    def declared_type(self) -> int: ...
    @property
    def declared_type_reading(self) -> str: ...
    @property
    def claimed(self) -> bool: ...
    @property
    def start_bytes(self) -> int: ...
    @property
    def length_bytes(self) -> int: ...
    @property
    def issue_category(self) -> str | None: ...
    @property
    def issue(self) -> str | None: ...

@final
class VolumeInfo:
    @property
    def id(self) -> int: ...
    @property
    def origin(self) -> str: ...
    @property
    def origin_regions(self) -> list[int]: ...
    @property
    def start_bytes(self) -> int: ...
    @property
    def length_bytes(self) -> int: ...
    @property
    def evidence(self) -> list[str]: ...
    @property
    def issues(self) -> list[str]: ...

@final
class FilesystemInfo:
    @property
    def id(self) -> int: ...
    @property
    def volume(self) -> int: ...
    @property
    def kind(self) -> str | None: ...
    @property
    def label(self) -> VolumeLabel | None: ...
    @property
    def cluster_bytes(self) -> int | None: ...
    @property
    def cluster_count(self) -> int | None: ...
    @property
    def sectors_per_track(self) -> int | None: ...
    @property
    def heads(self) -> int | None: ...
    @property
    def cylinders(self) -> int | None: ...
    @property
    def evidence(self) -> list[str]: ...
    @property
    def issues(self) -> list[str]: ...

@final
class VolumeLabel:
    @property
    def name(self) -> str | None: ...
    @property
    def answered_by(self) -> str | None: ...
    @property
    def readings(self) -> list[LabelReading]: ...

@final
class LabelReading:
    @property
    def source(self) -> str: ...
    @property
    def stored(self) -> str | None: ...

# ------------------------------------------------------- DOS drive letters

@final
class DosMachine:
    """The asserted DOS machine a drive-letter composition runs over."""

    def __init__(self) -> None: ...
    def assert_floppy(self, slot: int, report: DiskReport, /) -> None: ...
    def assert_fixed_disk(self, order: int, report: DiskReport, /) -> None: ...
    def assert_cdrom(self, order: int, *, letter: str | None = None) -> None: ...
    def declare_condition(self, condition: str, /) -> None: ...
    def compose(self, rule: str | None = None, /) -> DriveMap: ...
    def __repr__(self) -> str: ...

@final
class DriveMap:
    @property
    def applied_rules(self) -> list[str]: ...
    @property
    def mappings(self) -> list[DriveMapping]: ...
    @property
    def provenance(self) -> list[str]: ...
    def letter(self, letter: str, /) -> DriveMapping | None: ...
    def established_count(self) -> int: ...
    def __repr__(self) -> str: ...

@final
class DriveMapping:
    @property
    def letter(self) -> str: ...
    @property
    def outcome(self) -> str: ...
    @property
    def device_kind(self) -> str | None: ...
    @property
    def device_index(self) -> int | None: ...
    @property
    def volume(self) -> int | None: ...
    @property
    def phantom_of(self) -> str | None: ...
    @property
    def reason(self) -> str | None: ...
    def __repr__(self) -> str: ...

@final
class DosAssignmentRule:
    @property
    def name(self) -> str: ...
    @property
    def reading(self) -> str: ...
    def __repr__(self) -> str: ...

# ------------------------------------------------------------ the flux rungs

@final
class DeclaredLoss:
    """What a reading did not carry, named rather than hidden (P29)."""

    @property
    def code(self) -> str: ...
    @property
    def detail(self) -> str: ...
    @property
    def count(self) -> int: ...
    def __repr__(self) -> str: ...

@final
class C1541Bitstream:
    """The family's pulses, clocked into bit cells under its read channel."""

    def inspect(self) -> BitstreamReport: ...
    @property
    def location_count(self) -> int: ...
    @property
    def backing_bytes(self) -> int: ...
    @property
    def resident_bytes(self) -> int: ...
    def materialize_bytestream(
        self, *, cache_bytes: int | None = None
    ) -> C1541Bytestream: ...
    def __repr__(self) -> str: ...

@final
class C1541Bytestream:
    """The bytes one declared group code resolved. It assigns nothing above a byte."""

    def inspect(self) -> BytestreamReport: ...
    @property
    def location_count(self) -> int: ...
    @property
    def backing_bytes(self) -> int: ...
    @property
    def resident_bytes(self) -> int: ...
    def location(self, track: int, /) -> LocationBytes: ...
    def recognize_sectors(self, *, cache_bytes: int | None = None) -> C1541Sectors:
        """Where "no byte here is a sector" ends — by stating what it derives."""

    def __repr__(self) -> str: ...

@final
class LocationBytes:
    """The framed bytes of one location."""

    @property
    def track(self) -> int: ...
    @property
    def bytes(self) -> int: ...
    def read_at(self, offset: int, length: int, /) -> bytes: ...
    def __repr__(self) -> str: ...

@final
class C1541Sectors:
    """The recording's own sectors, each record carrying its evidence."""

    def inspect(self) -> SectorReport: ...
    def read_sector(self, track: int, sector: int, /) -> bytes:
        """Refuses by name — its own `SectorRule` set — rather than filling in."""

    def partition(self) -> Partition: ...
    @property
    def claim_count(self) -> int: ...
    @property
    def location_count(self) -> int: ...
    @property
    def backing_bytes(self) -> int: ...
    @property
    def resident_bytes(self) -> int: ...
    def __repr__(self) -> str: ...

@final
class BitstreamReport:
    @property
    def profile_id(self) -> str: ...
    @property
    def profile_name(self) -> str: ...
    @property
    def profile_version(self) -> int: ...
    @property
    def reference_clock_hz(self) -> int: ...
    @property
    def cycles_per_rotation(self) -> int: ...
    @property
    def locations(self) -> list[BitstreamLocation]: ...
    @property
    def declared_loss(self) -> list[DeclaredLoss]: ...
    @property
    def evidence(self) -> list[str]: ...
    def __repr__(self) -> str: ...

@final
class BitstreamLocation:
    @property
    def half_track_numerator(self) -> int: ...
    @property
    def half_track_denominator(self) -> int: ...
    @property
    def surface(self) -> int | None: ...
    @property
    def zone(self) -> int: ...
    @property
    def cell_cycles_numerator(self) -> int: ...
    @property
    def cell_cycles_denominator(self) -> int: ...
    @property
    def cells(self) -> int: ...
    @property
    def one_bits(self) -> int: ...
    @property
    def recorded_bits(self) -> int: ...
    @property
    def resolved_bits(self) -> int: ...
    @property
    def short_cells(self) -> int: ...
    @property
    def longest_zero_run(self) -> int: ...
    @property
    def wrap_slack_numerator(self) -> int: ...
    def __repr__(self) -> str: ...

@final
class BytestreamReport:
    @property
    def profile_id(self) -> str: ...
    @property
    def codec_id(self) -> str: ...
    @property
    def codec_name(self) -> str: ...
    @property
    def symbol_bits(self) -> int: ...
    @property
    def data_bits(self) -> int: ...
    @property
    def symbols_per_byte(self) -> int: ...
    @property
    def locations(self) -> list[BytestreamLocation]: ...
    @property
    def declared_loss(self) -> list[DeclaredLoss]: ...
    @property
    def evidence(self) -> list[str]: ...
    def __repr__(self) -> str: ...

@final
class BytestreamLocation:
    @property
    def half_track_numerator(self) -> int: ...
    @property
    def half_track_denominator(self) -> int: ...
    @property
    def surface(self) -> int | None: ...
    @property
    def bytes(self) -> int: ...
    @property
    def resolved_bytes(self) -> int: ...
    @property
    def unassigned_groups(self) -> int: ...
    @property
    def alignments(self) -> int: ...
    @property
    def longest_landmark_bits(self) -> int: ...
    @property
    def unframed_bits(self) -> int: ...
    def __repr__(self) -> str: ...

@final
class SectorReport:
    @property
    def profile_id(self) -> str: ...
    @property
    def grammar_id(self) -> str: ...
    @property
    def grammar_name(self) -> str: ...
    @property
    def payload_bytes(self) -> int: ...
    @property
    def locations(self) -> list[SectorLocation]: ...
    @property
    def claims(self) -> list[SectorClaim]: ...
    @property
    def contested(self) -> list[ContestedAddress]: ...
    @property
    def declared_loss(self) -> list[DeclaredLoss]: ...
    @property
    def evidence(self) -> list[str]: ...
    def __repr__(self) -> str: ...

@final
class SectorLocation:
    @property
    def half_track_numerator(self) -> int: ...
    @property
    def half_track_denominator(self) -> int: ...
    @property
    def surface(self) -> int | None: ...
    @property
    def records_declared(self) -> int | None: ...
    @property
    def headers(self) -> int: ...
    @property
    def records(self) -> int: ...
    @property
    def readable(self) -> int: ...
    @property
    def failed_checksum(self) -> int: ...
    @property
    def runs_without_a_record(self) -> int: ...
    def __repr__(self) -> str: ...

@final
class SectorClaim:
    @property
    def half_track_numerator(self) -> int: ...
    @property
    def half_track_denominator(self) -> int: ...
    @property
    def surface(self) -> int | None: ...
    @property
    def at_bit(self) -> int: ...
    @property
    def track(self) -> int: ...
    @property
    def sector(self) -> int: ...
    @property
    def id_high(self) -> int: ...
    @property
    def id_low(self) -> int: ...
    @property
    def header_checksum_stated(self) -> int: ...
    @property
    def header_checksum_computed(self) -> int: ...
    @property
    def has_data(self) -> bool: ...
    @property
    def data_at_bit(self) -> int: ...
    @property
    def data_checksum_stated(self) -> int: ...
    @property
    def data_checksum_computed(self) -> int: ...
    @property
    def unresolved_bytes(self) -> int: ...
    @property
    def within_declaration(self) -> bool: ...
    @property
    def readable(self) -> bool: ...
    @property
    def rule(self) -> str | None: ...
    @property
    def refusal(self) -> str | None: ...
    def __repr__(self) -> str: ...

@final
class ContestedAddress:
    """One address several readable claims state, holding different bytes.

    Reported, never resolved.
    """

    @property
    def track(self) -> int: ...
    @property
    def sector(self) -> int: ...
    @property
    def readable_claims(self) -> int: ...
    def __repr__(self) -> str: ...

# ------------------------------------------------- the .remanence flux root

@final
class FluxImage:
    """A `.remanence` artifact: the physical facts of one disk."""

    def __init__(self, path: _Path, *, cache_bytes: int | None = None) -> None: ...
    def inspect(self) -> FluxImageReport: ...
    @property
    def path(self) -> str | None: ...
    @property
    def format_id(self) -> str: ...
    @property
    def format_name(self) -> str: ...
    @property
    def access_mode(self) -> str | None: ...
    @property
    def backing_bytes(self) -> int: ...
    @property
    def resident_bytes(self) -> int: ...
    def write(self, path: _Path, /) -> FluxWriteReport: ...
    def describe_d64(self) -> D64Report:
        """Computes everything and writes nothing."""

    def write_d64(self, path: _Path, /) -> D64Report: ...
    def describe_g64(self) -> G64Report: ...
    def write_g64(self, path: _Path, /) -> G64Report: ...
    def describe_p64(self) -> P64Report: ...
    def write_p64(self, path: _Path, /) -> P64Report: ...
    def materialize_c1541_bitstream(
        self, *, cache_bytes: int | None = None
    ) -> C1541Bitstream:
        """The qualifier stays: this receiver is no c1541 type."""

    def close(self) -> None: ...
    def __enter__(self) -> FluxImage: ...
    def __exit__(self, exc_type: object, exc: object, tb: object, /) -> bool: ...
    def __repr__(self) -> str: ...

@final
class FluxImageReport:
    @property
    def form_factor(self) -> str: ...
    @property
    def angular_divisions(self) -> int: ...
    @property
    def holes(self) -> list[FluxHole]: ...
    @property
    def surfaces(self) -> list[int]: ...
    @property
    def orbits(self) -> list[FluxOrbit]: ...
    @property
    def provenance(self) -> list[str]: ...
    def __repr__(self) -> str: ...

@final
class FluxHole:
    """One index hole: a fraction of a turn for the centre, another for the extent."""

    @property
    def center_numerator(self) -> int: ...
    @property
    def center_denominator(self) -> int: ...
    @property
    def extent_numerator(self) -> int: ...
    @property
    def extent_denominator(self) -> int: ...
    def __repr__(self) -> str: ...

@final
class FluxOrbit:
    @property
    def surface(self) -> int: ...
    @property
    def radius_microns(self) -> int: ...
    @property
    def points(self) -> int: ...
    @property
    def coherent_points(self) -> int: ...
    @property
    def unaligned_spans(self) -> int: ...
    def __repr__(self) -> str: ...

@final
class FluxWriteReport:
    @property
    def path(self) -> str: ...
    @property
    def artifact_bytes(self) -> int: ...
    @property
    def orbits(self) -> int: ...
    @property
    def points(self) -> int: ...
    @property
    def declared_loss(self) -> list[DeclaredLoss]: ...
    def __repr__(self) -> str: ...

# ------------------------------------------------------- the C64 renditions

@final
class D64Report:
    @property
    def path(self) -> str | None: ...
    @property
    def artifact_bytes(self) -> int: ...
    @property
    def blocks_read(self) -> int: ...
    @property
    def blocks_defined(self) -> int: ...
    @property
    def failed_checksums(self) -> int: ...
    @property
    def missing(self) -> list[D64Block]: ...
    @property
    def declared_loss(self) -> list[DeclaredLoss]: ...
    def __repr__(self) -> str: ...

@final
class D64Block:
    @property
    def track(self) -> int: ...
    @property
    def sector(self) -> int: ...
    def __repr__(self) -> str: ...

@final
class G64Report:
    @property
    def path(self) -> str | None: ...
    @property
    def artifact_bytes(self) -> int: ...
    @property
    def half_tracks(self) -> list[G64HalfTrack]: ...
    @property
    def declared_loss(self) -> list[DeclaredLoss]: ...
    def __repr__(self) -> str: ...

@final
class G64HalfTrack:
    @property
    def index(self) -> int: ...
    @property
    def bits(self) -> int: ...
    @property
    def speed_zone(self) -> int: ...
    @property
    def clocked_at_nominal(self) -> bool: ...
    def __repr__(self) -> str: ...

@final
class P64Report:
    @property
    def format_id(self) -> str: ...
    @property
    def format_name(self) -> str: ...
    @property
    def version(self) -> int: ...
    @property
    def write_protected(self) -> bool: ...
    @property
    def double_sided(self) -> bool: ...
    @property
    def profile_id(self) -> str: ...
    @property
    def reference_clock_hz(self) -> int: ...
    @property
    def cycles_per_rotation(self) -> int: ...
    @property
    def half_tracks(self) -> list[P64HalfTrack]: ...
    @property
    def declared_loss(self) -> list[DeclaredLoss]: ...
    @property
    def evidence(self) -> list[str]: ...
    def __repr__(self) -> str: ...

@final
class P64HalfTrack:
    @property
    def index(self) -> int: ...
    @property
    def side(self) -> int: ...
    @property
    def half_track_numerator(self) -> int: ...
    @property
    def half_track_denominator(self) -> int: ...
    @property
    def pulses(self) -> int: ...
    @property
    def strong_pulses(self) -> int: ...
    @property
    def weak_pulses(self) -> int: ...
    @property
    def absent_pulses(self) -> int: ...
    def __repr__(self) -> str: ...
